"""example sentences for the «Темы» group (everyday vocabulary)

Revision ID: 0018
Revises: 0017
Create Date: 2026-05-22

Content upgrade batch 2: the whole «Темы» group (everyday single words) had 0%
example coverage. Hand-authored, simple and level-appropriate, each sentence
uses the word in its intended sense. Idempotent: only fills words whose example
is still NULL; downgrade clears only the exact examples it set.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None


EXAMPLES: dict[str, str] = {
    "abroad": "She studied abroad for a year.",
    "account": "I opened a new bank account.",
    "afraid": "He is afraid of the dark.",
    "afternoon": "Let's meet in the afternoon.",
    "airport": "We arrived at the airport early.",
    "angry": "She was angry about the delay.",
    "anxious": "I felt anxious before the exam.",
    "app": "I downloaded a new app today.",
    "apple": "She ate a red apple.",
    "arm": "He broke his arm playing football.",
    "arrival": "Check the arrival time of the flight.",
    "arrive": "We will arrive at noon.",
    "aunt": "My aunt lives in Spain.",
    "back": "My back hurts after work.",
    "banana": "Monkeys love to eat bananas.",
    "bank": "I need to go to the bank.",
    "basketball": "They play basketball after school.",
    "bathroom": "The bathroom is down the hall.",
    "battery": "My phone battery is almost dead.",
    "bear": "A bear lives in the forest.",
    "bed": "She made her bed in the morning.",
    "bedroom": "Her bedroom has a big window.",
    "belt": "He wears a leather belt.",
    "bill": "Can I have the bill, please?",
    "bird": "A bird is singing outside.",
    "black": "He wore a black suit.",
    "blanket": "She covered the baby with a blanket.",
    "blockchain": "Bitcoin runs on a blockchain.",
    "blood": "The nurse took a blood sample.",
    "blue": "The sky is blue today.",
    "boarding": "Boarding starts in ten minutes.",
    "boots": "Wear your boots, it's snowing.",
    "bored": "The kids were bored at home.",
    "borrow": "Can I borrow your pen?",
    "boss": "My boss gave me a new task.",
    "brain": "The brain controls the body.",
    "branch": "A bird sat on the branch.",
    "bread": "She bought fresh bread.",
    "breakfast": "I had eggs for breakfast.",
    "breath": "Take a deep breath and relax.",
    "breeze": "A cool breeze came from the sea.",
    "bridge": "We walked across the bridge.",
    "brother": "My brother is older than me.",
    "brown": "She has brown eyes.",
    "budget": "The project is over budget.",
    "bug": "There is a bug in the code.",
    "build": "The build failed on the server.",
    "building": "That building is very tall.",
    "bus": "I take the bus to work.",
    "butter": "He spread butter on the toast.",
    "button": "Press the green button to start.",
    "calm": "Stay calm and breathe.",
    "camping": "We went camping in the mountains.",
    "carpet": "There is a soft carpet on the floor.",
    "cash": "I paid in cash.",
    "cat": "The cat is sleeping on the sofa.",
    "ceiling": "The lamp hangs from the ceiling.",
    "chair": "Please take a chair.",
    "chalkboard": "The teacher wrote on the chalkboard.",
    "charger": "I forgot my phone charger.",
    "cheese": "I like cheese on my pizza.",
    "chess": "They played chess all evening.",
    "chest": "He felt a pain in his chest.",
    "chicken": "We had chicken for dinner.",
    "child": "The child is playing in the park.",
    "classroom": "The classroom was full of students.",
    "client": "Our client approved the design.",
    "cloud": "There is not a single cloud in the sky.",
    "cloudy": "It is cloudy and grey today.",
    "coach": "The coach trains the team daily.",
    "coat": "Put on your coat, it's cold.",
    "coffee": "I drink coffee every morning.",
    "colleague": "My colleague helped me with the report.",
    "commit": "Commit your changes before you leave.",
    "computer": "She works on her computer all day.",
    "confident": "He felt confident before the interview.",
    "confused": "I was confused by the instructions.",
    "contract": "They signed a two-year contract.",
    "corner": "The shop is on the corner.",
    "cost": "The cost of living keeps rising.",
    "cough": "He has a bad cough.",
    "cousin": "My cousin visits us every summer.",
    "cow": "The cow gives fresh milk.",
    "crossroads": "Turn left at the crossroads.",
    "curious": "Children are naturally curious.",
    "currency": "The local currency is the euro.",
    "curtain": "She opened the curtains in the morning.",
    "customs": "We passed through customs quickly.",
    "cycling": "Cycling is good for your health.",
    "dancing": "She loves dancing at parties.",
    "daughter": "Their daughter starts school this year.",
    "deadline": "The deadline is next Friday.",
    "debt": "He paid off all his debt.",
    "decide": "I can't decide what to order.",
    "degree": "She has a degree in biology.",
    "delay": "There was a long delay at the airport.",
    "delicious": "The cake was delicious.",
    "departure": "Check the departure time on the board.",
    "deploy": "We deploy the app every Friday.",
    "device": "This device connects to wifi.",
    "dinner": "We had dinner at eight.",
    "diploma": "He received his diploma yesterday.",
    "disappointed": "She was disappointed with the result.",
    "discount": "They offered a twenty percent discount.",
    "disease": "The disease spread quickly.",
    "doctor": "You should see a doctor.",
    "dog": "The dog barked at the stranger.",
    "download": "I downloaded the file.",
    "drawer": "The keys are in the top drawer.",
    "dress": "She wore a blue dress.",
    "duck": "A duck swam across the pond.",
    "ear": "He whispered in my ear.",
    "earn": "She earns a good salary.",
    "egg": "I boiled an egg for breakfast.",
    "elephant": "The elephant is a huge animal.",
    "embarrassed": "He felt embarrassed by the mistake.",
    "employee": "The company hired a new employee.",
    "essay": "I wrote an essay about climate change.",
    "evening": "We watch films in the evening.",
    "exam": "I have an exam tomorrow.",
    "exchange": "She works at a crypto exchange.",
    "excited": "The kids were excited about the trip.",
    "expect": "We expect good weather tomorrow.",
    "expense": "Travel is a big expense.",
    "explain": "Can you explain this rule?",
    "eye": "She closed her eyes and slept.",
    "face": "He washed his face.",
    "fare": "The bus fare went up this year.",
    "father": "My father taught me to drive.",
    "feature": "The app has a new feature.",
    "fever": "The child has a high fever.",
    "file": "Save the file before closing.",
    "finger": "She cut her finger.",
    "fish": "We caught a big fish.",
    "fishing": "He goes fishing on weekends.",
    "fix": "This fix solves the bug.",
    "flight": "Our flight was delayed.",
    "floor": "The keys fell on the floor.",
    "fog": "Thick fog covered the road.",
    "folder": "Put the file in this folder.",
    "foot": "My foot hurts after the walk.",
    "football": "They watched the football match.",
    "forecast": "The forecast says it will rain.",
    "forget": "Don't forget your keys.",
    "fox": "A fox ran across the field.",
    "freezing": "It is freezing outside.",
    "friday": "We meet every Friday.",
    "fruit": "Eat more fruit and vegetables.",
    "furniture": "We bought new furniture for the flat.",
    "gate": "The plane leaves from gate twelve.",
    "gloves": "Wear gloves, it's cold.",
    "gold": "She wore a gold ring.",
    "grade": "He got a good grade on the test.",
    "grandfather": "My grandfather tells great stories.",
    "grandmother": "Grandmother baked a pie.",
    "grape": "These grapes are very sweet.",
    "grateful": "I am grateful for your help.",
    "green": "The grass is green.",
    "grey": "The sky turned grey.",
    "growth": "The company saw rapid growth.",
    "guess": "Can you guess my age?",
    "guitar": "He plays the guitar well.",
    "gym": "I go to the gym three times a week.",
    "hair": "She has long brown hair.",
    "hand": "He raised his hand to ask a question.",
    "happy": "I am happy to see you.",
    "hat": "He wore a warm hat.",
    "head": "I have a pain in my head.",
    "headache": "I have a terrible headache.",
    "health": "Exercise is good for your health.",
    "healthy": "She eats a healthy diet.",
    "heart": "His heart beats fast when he runs.",
    "hiking": "We went hiking in the hills.",
    "hire": "The firm wants to hire two engineers.",
    "hobby": "Painting is my favourite hobby.",
    "homework": "Finish your homework first.",
    "horse": "She rides a horse every weekend.",
    "hospital": "He was taken to the hospital.",
    "hotel": "We stayed in a small hotel.",
    "hour": "The trip takes an hour.",
    "humid": "The air is hot and humid.",
    "husband": "Her husband cooks every evening.",
    "illness": "He missed work due to illness.",
    "improve": "I want to improve my English.",
    "income": "Their monthly income is stable.",
    "injury": "The player has a knee injury.",
    "internet": "The internet is down again.",
    "interview": "I have a job interview tomorrow.",
    "issue": "We solved the main issue.",
    "jacket": "Put on your jacket.",
    "jealous": "He felt jealous of his friend.",
    "jeans": "She wears blue jeans.",
    "journey": "The journey took two days.",
    "juice": "I drink orange juice in the morning.",
    "keyboard": "My keyboard stopped working.",
    "kitchen": "She is cooking in the kitchen.",
    "knee": "He hurt his knee.",
    "knowledge": "She has deep knowledge of history.",
    "lamp": "Turn on the lamp, please.",
    "laptop": "I work on my laptop.",
    "learn": "I want to learn to cook.",
    "leave": "I have to leave early today.",
    "lecture": "The lecture starts at nine.",
    "ledger": "Every payment is recorded in the ledger.",
    "leg": "He broke his leg skiing.",
    "lesson": "Today's lesson was about verbs.",
    "library": "She studies at the library.",
    "lightning": "Lightning lit up the sky.",
    "lion": "The lion is the king of animals.",
    "loan": "He took a loan to buy a car.",
    "lonely": "She felt lonely in the new city.",
    "lose": "Try not to lose your ticket.",
    "luggage": "I lost my luggage at the airport.",
    "lunch": "Let's have lunch together.",
    "manager": "The manager approved the plan.",
    "map": "We looked at the map.",
    "match": "We watched the football match.",
    "meat": "He doesn't eat meat.",
    "medicine": "Take this medicine twice a day.",
    "meeting": "The meeting starts at ten.",
    "merge": "Merge the branch before the release.",
    "mild": "The weather is mild today.",
    "milk": "She drinks a glass of milk.",
    "miner": "Miners add new blocks to the chain.",
    "minute": "Wait a minute, please.",
    "mirror": "She looked in the mirror.",
    "monday": "I start work on Monday.",
    "money": "He saved a lot of money.",
    "monkey": "The monkey climbed the tree.",
    "month": "We move next month.",
    "morning": "I run every morning.",
    "mother": "My mother makes great soup.",
    "mouse": "The cat caught a mouse.",
    "mouth": "Open your mouth and say ah.",
    "neck": "She wore a scarf around her neck.",
    "nervous": "I get nervous before speaking.",
    "network": "The office network is slow.",
    "night": "We arrived late at night.",
    "nose": "He has a cold and a runny nose.",
    "notebook": "Write it in your notebook.",
    "nurse": "The nurse checked my temperature.",
    "office": "She works in a big office.",
    "onion": "Chop the onion finely.",
    "orange": "He painted the wall orange.",
    "pain": "She felt a sharp pain in her arm.",
    "painting": "Painting helps her relax.",
    "parent": "Every parent worries about their kids.",
    "park": "We walked in the park.",
    "passport": "Don't forget your passport.",
    "password": "Enter your password to log in.",
    "patient": "The doctor saw the patient.",
    "pencil": "Draw it with a pencil.",
    "pharmacy": "I bought medicine at the pharmacy.",
    "phone": "She answered the phone.",
    "pig": "The pig rolled in the mud.",
    "pink": "She wore a pink dress.",
    "platform": "The train leaves from platform three.",
    "pocket": "He put the keys in his pocket.",
    "potato": "We had potatoes for dinner.",
    "price": "The price went up again.",
    "profit": "The company made a big profit.",
    "project": "We finished the project on time.",
    "promotion": "She got a promotion at work.",
    "proud": "His parents are proud of him.",
    "pupil": "Each pupil has a notebook.",
    "purple": "She loves purple flowers.",
    "rabbit": "The rabbit ran into the bushes.",
    "rain": "The rain stopped at noon.",
    "rainbow": "A rainbow appeared after the rain.",
    "recover": "He is starting to recover from the flu.",
    "red": "She painted the door red.",
    "relative": "A relative is visiting us.",
    "release": "The new release ships on Monday.",
    "relieved": "I felt relieved after the exam.",
    "remember": "Do you remember her name?",
    "report": "Send me the report by Friday.",
    "reservation": "I made a reservation for two.",
    "resume": "Send your resume to HR.",
    "revenue": "The company's revenue grew this year.",
    "review": "Please review my pull request.",
    "rice": "She cooked rice for dinner.",
    "rich": "He became rich after the deal.",
    "road": "The road was empty at night.",
    "running": "Running keeps me fit.",
    "sad": "She felt sad after the news.",
    "salad": "I ordered a green salad.",
    "salary": "She earns a good monthly salary.",
    "salt": "Add a little salt to the soup.",
    "saturday": "We relax on Saturday.",
    "save": "Save some money for the trip.",
    "scarf": "She wore a warm scarf.",
    "schedule": "Check my schedule for tomorrow.",
    "score": "The final score was two to one.",
    "screen": "The screen is too bright.",
    "second": "Wait a second, please.",
    "semester": "The new semester begins in autumn.",
    "sheep": "The sheep grazed in the field.",
    "shelf": "Put the book on the shelf.",
    "ship": "We ship new features every week.",
    "shirt": "He ironed his white shirt.",
    "shoes": "These shoes are too small.",
    "shoulder": "She carried the bag on her shoulder.",
    "sick": "I feel sick today.",
    "sidewalk": "Walk on the sidewalk, not the road.",
    "signpost": "The signpost points to the station.",
    "sister": "My sister plays the piano.",
    "skill": "Communication is a useful skill.",
    "skin": "The cream is good for dry skin.",
    "skirt": "She bought a long skirt.",
    "sleeve": "He rolled up his sleeves.",
    "snake": "A snake slid through the grass.",
    "snow": "Snow covered the streets.",
    "socks": "He put on clean socks.",
    "sofa": "We sat on the sofa to watch a film.",
    "software": "The software needs an update.",
    "son": "Their son is learning to walk.",
    "soup": "She made tomato soup.",
    "souvenir": "I bought a souvenir for my sister.",
    "spend": "I spent the weekend reading.",
    "sport": "Football is my favourite sport.",
    "square": "The market is on the main square.",
    "stairs": "She ran up the stairs.",
    "stake": "You can stake your tokens to earn rewards.",
    "stakeholder": "We must align with every stakeholder.",
    "station": "I waited at the station.",
    "stay": "We will stay two more days.",
    "stomach": "My stomach hurts after lunch.",
    "storm": "A storm is coming tonight.",
    "street": "The street was full of people.",
    "student": "She is a hard-working student.",
    "subject": "Maths is my favourite subject.",
    "subway": "I take the subway to work.",
    "sugar": "He adds sugar to his tea.",
    "suit": "He wore a black suit to the meeting.",
    "suitcase": "I packed my suitcase last night.",
    "sun": "The sun is shining brightly.",
    "sunday": "We rest on Sunday.",
    "sunny": "It is a sunny day.",
    "surprised": "She was surprised by the gift.",
    "sweater": "Wear a warm sweater.",
    "swimming": "Swimming is great exercise.",
    "table": "Put the plates on the table.",
    "task": "I finished the first task.",
    "tax": "Everyone has to pay tax.",
    "taxi": "We took a taxi to the hotel.",
    "tea": "She drinks tea with lemon.",
    "teach": "She teaches English to children.",
    "teacher": "Our teacher is very kind.",
    "team": "The whole team worked late.",
    "temperature": "The temperature dropped overnight.",
    "tennis": "They play tennis on Sundays.",
    "test": "I passed the driving test.",
    "thunder": "Thunder woke up the children.",
    "thursday": "The class meets on Thursday.",
    "ticket": "I bought a one-way ticket.",
    "tie": "He wore a red tie.",
    "tiger": "The tiger has orange fur.",
    "today": "I'm very busy today.",
    "token": "The new token launched today.",
    "tomato": "Slice the tomato for the salad.",
    "tomorrow": "See you tomorrow.",
    "tooth": "The child lost a tooth.",
    "tourist": "The city is full of tourists.",
    "trade": "He works in international trade.",
    "traffic": "There was heavy traffic this morning.",
    "train": "The train arrives at six.",
    "treatment": "The treatment lasted two weeks.",
    "trip": "We are planning a trip to Italy.",
    "trousers": "He bought new trousers.",
    "tuesday": "The meeting is on Tuesday.",
    "uncle": "My uncle is a doctor.",
    "university": "She studies at a university.",
    "update": "Install the latest update.",
    "upload": "Upload the photo to the site.",
    "vegetable": "Carrots are my favourite vegetable.",
    "wait": "Please wait a few minutes.",
    "wall": "There is a picture on the wall.",
    "wallet": "I left my wallet at home.",
    "water": "Drink plenty of water.",
    "weather": "The weather is lovely today.",
    "website": "Our website is down.",
    "wednesday": "We have a call on Wednesday.",
    "week": "I'll see you next week.",
    "white": "She wore a white dress.",
    "wife": "His wife is a teacher.",
    "win": "Our team hopes to win.",
    "wind": "The wind is strong today.",
    "window": "Open the window for fresh air.",
    "windy": "It is windy by the sea.",
    "wolf": "A wolf howled in the night.",
    "year": "We met a year ago.",
    "yellow": "The lemon is bright yellow.",
    "yesterday": "I called you yesterday.",
    "yield": "These bonds offer a high yield.",
}


def upgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET example_sentence = :e "
        "WHERE track = 'en' AND normalized_word = :n AND example_sentence IS NULL"
    )
    for normalized, example in EXAMPLES.items():
        conn.execute(stmt, {"e": example, "n": normalized})


def downgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET example_sentence = NULL "
        "WHERE track = 'en' AND normalized_word = :n AND example_sentence = :e"
    )
    for normalized, example in EXAMPLES.items():
        conn.execute(stmt, {"e": example, "n": normalized})
