"""example sentences for the «Уровни» group (the A1→B2 course spine)

Revision ID: 0019
Revises: 0018
Create Date: 2026-05-22

Content upgrade batch 3: fills the remaining level words (the course spine) that
still had no example. Hand-authored, sense-matched, level-appropriate. Idempotent
(only NULL examples); downgrade clears only the exact examples it set.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


EXAMPLES: dict[str, str] = {
    # A1
    "answer": "She gave the right answer.",
    "ask": "Can I ask you a question?",
    "bad": "The weather was bad all day.",
    "beautiful": "What a beautiful sunset!",
    "big": "They live in a big house.",
    "book": "I read a good book last night.",
    "call": "I'll call you tomorrow.",
    "car": "He washed his car.",
    "choose": "You can choose any seat.",
    "city": "London is a huge city.",
    "close": "Please close the door.",
    "cold": "The water is too cold.",
    "cook": "She loves to cook dinner.",
    "day": "It was a long day at work.",
    "door": "Someone is at the door.",
    "early": "I woke up early today.",
    "family": "He has a big family.",
    "fast": "That car is very fast.",
    "fly": "Birds fly south in winter.",
    "food": "The food here is great.",
    "friend": "She is my best friend.",
    "good": "This is a good idea.",
    "grow": "Plants grow in the sun.",
    "hard": "The exam was very hard.",
    "help": "Can you help me, please?",
    "here": "Come here for a moment.",
    "high": "The mountain is very high.",
    "home": "I stayed home all day.",
    "hot": "The soup is too hot.",
    "house": "They bought a new house.",
    "late": "Sorry I'm late.",
    "like": "I like this song.",
    "live": "They live near the sea.",
    "long": "It was a long trip.",
    "love": "I love this city.",
    "low": "Prices are very low now.",
    "man": "A man asked for directions.",
    "move": "Let's move to the next room.",
    "name": "What is your name?",
    "need": "I need some help.",
    "new": "She has a new phone.",
    "nice": "Have a nice day!",
    "now": "I am busy right now.",
    "number": "Give me your phone number.",
    "old": "This is an old building.",
    "open": "The shop is open.",
    "people": "Many people came to the party.",
    "place": "This is a quiet place.",
    "play": "Children play in the yard.",
    "put": "Put the book on the table.",
    "question": "I have a quick question.",
    "ready": "Are you ready to go?",
    "right": "You gave the right answer.",
    "room": "The room is very clean.",
    "school": "The kids go to school.",
    "short": "It was a short meeting.",
    "slow": "The internet is slow today.",
    "small": "She has a small dog.",
    "start": "Let's start the lesson.",
    "stop": "The bus stopped here.",
    "strong": "He is very strong.",
    "sure": "I am sure about it.",
    "time": "What time is it?",
    "try": "Try this dish.",
    "turn": "Turn left at the corner.",
    "use": "I use this app daily.",
    "walk": "We walk to school.",
    "want": "I want a cup of tea.",
    "warm": "It is warm today.",
    "wash": "Wash your hands.",
    "weak": "He felt weak after the flu.",
    "wear": "She likes to wear red.",
    "woman": "A woman called for you.",
    "word": "I don't know this word.",
    "work": "I work from home.",
    "wrong": "You took the wrong bus.",
    # A2
    "accept": "She accepted the job offer.",
    "affect": "Stress can affect your health.",
    "agree": "I agree with you.",
    "allow": "Smoking is not allowed here.",
    "appreciate": "I really appreciate your help.",
    "arrange": "Let's arrange a meeting.",
    "attend": "He attends every class.",
    "attract": "The show attracts many tourists.",
    "avoid": "Try to avoid mistakes.",
    "blame": "Don't blame yourself.",
    "celebrate": "We celebrate her birthday today.",
    "cheap": "This phone is cheap.",
    "comfortable": "The bed is very comfortable.",
    "compare": "Compare the two options.",
    "complete": "I completed the task.",
    "connect": "Connect the cable here.",
    "consider": "Please consider my idea.",
    "contain": "This box contains books.",
    "continue": "Continue reading, please.",
    "control": "He can't control his temper.",
    "create": "She created a new design.",
    "dangerous": "That road is dangerous.",
    "deliver": "They deliver food at night.",
    "deny": "He denied the charge.",
    "describe": "Describe what you saw.",
    "design": "She designs websites.",
    "develop": "We develop new apps.",
    "different": "These two are different.",
    "difficult": "This is a difficult choice.",
    "disappear": "The sun disappeared behind a cloud.",
    "discover": "Scientists discovered a new planet.",
    "discuss": "Let's discuss the plan.",
    "divide": "Divide the cake into eight.",
    "easy": "The test was easy.",
    "enjoy": "I enjoy long walks.",
    "escape": "The cat escaped from the house.",
    "exist": "Dragons don't exist.",
    "expensive": "This watch is expensive.",
    "explore": "We explored the old town.",
    "express": "She can't express her feelings.",
    "hate": "I hate waiting in line.",
    "hope": "I hope you feel better.",
    "hurry": "Hurry up, we're late.",
    "imagine": "Imagine a quiet beach.",
    "important": "This is an important meeting.",
    "introduce": "Let me introduce my friend.",
    "invite": "They invited us to dinner.",
    "join": "Join us for lunch.",
    "lend": "Can you lend me a pen?",
    "manage": "She manages a small team.",
    "matter": "Your opinion matters to me.",
    "measure": "Measure the table first.",
    "mix": "Mix the flour and sugar.",
    "notice": "I didn't notice the sign.",
    "offer": "They offered me a discount.",
    "order": "I'd like to order a pizza.",
    "owe": "I owe you ten dollars.",
    "paint": "We painted the wall blue.",
    "possible": "It's possible to finish today.",
    "prefer": "I prefer tea to coffee.",
    "prepare": "I prepared dinner for two.",
    "press": "Press the button twice.",
    "prevent": "Exercise can prevent illness.",
    "protect": "Wear a hat to protect your head.",
    "provide": "The hotel provides towels.",
    "pull": "Pull the door to open it.",
    "push": "Push the cart slowly.",
    "realize": "I realized my mistake too late.",
    "receive": "I received your message.",
    "recognize": "I didn't recognize you.",
    "recommend": "Can you recommend a book?",
    "reduce": "We must reduce costs.",
    "refuse": "She refused to help.",
    "relax": "I relax by reading.",
    "rely": "You can rely on me.",
    "rent": "They rent a small flat.",
    "repair": "He repaired the bike.",
    "repeat": "Could you repeat that?",
    "rescue": "Firefighters rescued the cat.",
    "respect": "I respect your decision.",
    "seem": "You seem tired today.",
    "share": "Let's share the bill.",
    "shout": "Don't shout at me.",
    "sign": "Please sign here.",
    "similar": "These two cars are similar.",
    "solve": "We solved the problem.",
    "steal": "Someone tried to steal my bike.",
    "succeed": "She worked hard to succeed.",
    "suggest": "I suggest we leave now.",
    "support": "Thanks for supporting me.",
    "surprise": "Let's surprise her with a cake.",
    "touch": "Don't touch the wet paint.",
    "travel": "I love to travel.",
    "trust": "I trust my doctor.",
    "waste": "Don't waste your time.",
    "wonder": "I wonder what happened.",
    # B1
    "accurate": "Her report was accurate.",
    "admit": "He admitted his mistake.",
    "advantage": "Speed is our main advantage.",
    "announce": "They announced the results.",
    "apologize": "I apologize for the delay.",
    "appropriate": "Wear appropriate clothes.",
    "argue": "They often argue about money.",
    "assume": "Don't assume the worst.",
    "attempt": "His first attempt failed.",
    "available": "Is the room available?",
    "aware": "Are you aware of the rules?",
    "behaviour": "His behaviour surprised me.",
    "benefit": "Exercise has many benefits.",
    "capable": "She is capable of more.",
    "challenge": "This job is a real challenge.",
    "common": "Smith is a common name.",
    "complain": "He likes to complain.",
    "complex": "This is a complex problem.",
    "conclusion": "We reached a conclusion.",
    "confirm": "Please confirm your booking.",
    "consequence": "Every action has a consequence.",
    "constant": "There was a constant noise.",
    "current": "What is the current price?",
    "decision": "It was a hard decision.",
    "define": "Can you define this word?",
    "development": "The development took years.",
    "difference": "There is a big difference.",
    "effect": "The medicine had no effect.",
    "efficient": "This engine is very efficient.",
    "effort": "Put more effort into it.",
    "encourage": "Teachers encourage students.",
    "ensure": "Ensure the door is locked.",
    "essential": "Water is essential for life.",
    "estimate": "Can you estimate the cost?",
    "evaluate": "We evaluate every plan.",
    "evidence": "There is no evidence yet.",
    "examine": "The doctor examined me.",
    "experience": "She has years of experience.",
    "factor": "Price is a key factor.",
    "flexible": "My schedule is flexible.",
    "frequent": "He is a frequent visitor.",
    "function": "Explain the function of this part.",
    "goal": "My goal is to learn English.",
    "impact": "The news had a big impact.",
    "indicate": "The sign indicates danger.",
    "influence": "Friends influence our choices.",
    "involve": "The job involves travel.",
    "major": "That was a major change.",
    "method": "We tried a new method.",
    "minor": "It was a minor issue.",
    "observe": "We observe the stars at night.",
    "obvious": "The answer is obvious.",
    "occur": "Mistakes sometimes occur.",
    "opinion": "In my opinion, it's fine.",
    "opportunity": "This is a great opportunity.",
    "particular": "I like this one in particular.",
    "perform": "The team performed well.",
    "persuade": "She persuaded me to go.",
    "predict": "No one can predict the future.",
    "previous": "See the previous chapter.",
    "process": "Learning is a slow process.",
    "progress": "She made good progress.",
    "propose": "I propose a new plan.",
    "purpose": "What is the purpose of this?",
    "quality": "The quality is excellent.",
    "range": "We sell a wide range of bikes.",
    "rare": "Rain is rare here in summer.",
    "react": "How did he react?",
    "recent": "In recent years, prices rose.",
    "relationship": "They have a close relationship.",
    "reliable": "He is a reliable worker.",
    "replace": "We must replace the battery.",
    "represent": "She represents our team.",
    "resource": "Water is a precious resource.",
    "responsibility": "Safety is everyone's responsibility.",
    "risk": "There is a small risk.",
    "role": "She plays a key role.",
    "seek": "We seek a fair solution.",
    "situation": "It's a difficult situation.",
    "society": "Technology changes society.",
    "solution": "We found a simple solution.",
    "source": "What is the source of the noise?",
    "specific": "Give me a specific example.",
    "structure": "The structure is very strong.",
    "struggle": "Many families struggle to pay rent.",
    "success": "Hard work leads to success.",
    "sudden": "There was a sudden noise.",
    "survive": "Few plants survive the winter.",
    "typical": "This is typical of him.",
    "value": "I value your friendship.",
    "various": "We tried various methods.",
    # B2
    "accumulate": "Dust accumulates on the shelf.",
    "acknowledge": "He acknowledged his error.",
    "adequate": "The pay is adequate.",
    "advocate": "She advocates for clean energy.",
    "ambiguous": "His answer was ambiguous.",
    "anticipate": "We anticipate strong demand.",
    "assert": "He asserted his innocence.",
    "assess": "Teachers assess the students.",
    "attribute": "She attributes her success to luck.",
    "bias": "The report shows a clear bias.",
    "coherent": "Write a coherent argument.",
    "comprehensive": "This is a comprehensive guide.",
    "compromise": "They reached a compromise.",
    "considerable": "It took considerable effort.",
    "constrain": "Budget constrains our plans.",
    "contradict": "The two reports contradict each other.",
    "controversial": "This is a controversial topic.",
    "convey": "Words can't convey my thanks.",
    "deduce": "We can deduce the answer.",
    "deliberate": "It was a deliberate choice.",
    "derive": "Many words derive from Latin.",
    "deteriorate": "His health began to deteriorate.",
    "diminish": "Interest in the show diminished.",
    "distinct": "There are two distinct types.",
    "diverse": "The team is very diverse.",
    "eliminate": "We must eliminate the risk.",
    "emerge": "New problems emerged.",
    "encounter": "We encountered a few issues.",
    "endure": "They endured hard times.",
    "enhance": "Music enhances the mood.",
    "exceed": "Costs exceeded the budget.",
    "explicit": "She gave explicit instructions.",
    "exploit": "They exploit cheap labour.",
    "facilitate": "This tool facilitates learning.",
    "feasible": "Is the plan feasible?",
    "fundamental": "Trust is fundamental to teamwork.",
    "hypothesis": "The data support the hypothesis.",
    "implication": "Consider the implications carefully.",
    "implicit": "There was an implicit warning.",
    "inevitable": "Change is inevitable.",
    "inherent": "There are inherent risks.",
    "intervene": "The teacher had to intervene.",
    "justify": "Nothing can justify violence.",
    "legitimate": "That is a legitimate concern.",
    "manipulate": "He tried to manipulate the vote.",
    "notion": "I reject that notion.",
    "ongoing": "It is an ongoing project.",
    "phenomenon": "This is a rare phenomenon.",
    "plausible": "That sounds plausible.",
    "prevail": "Common sense will prevail.",
    "profound": "The book had a profound effect.",
    "prominent": "She is a prominent scientist.",
    "rational": "Make a rational decision.",
    "reinforce": "This reinforces my point.",
    "scope": "The scope of the project grew.",
    "subsequent": "In subsequent years, it improved.",
    "subtle": "There is a subtle difference.",
    "underlying": "What is the underlying cause?",
    "undermine": "Doubt can undermine confidence.",
    "viable": "It is a viable option.",
}


def upgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET example_sentence = :e "
        "WHERE track = 'en' AND normalized_word = :n AND example_sentence IS NULL"
    )
    for normalized, example in EXAMPLES.items():
        conn.execute(stmt, {"e": example, "n": normalized})


def downgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET example_sentence = NULL "
        "WHERE track = 'en' AND normalized_word = :n AND example_sentence = :e"
    )
    for normalized, example in EXAMPLES.items():
        conn.execute(stmt, {"e": example, "n": normalized})
