"""CEFR level + frequency rank for the 1116 words that had neither.

Word.level existed but was filled only for the graded level packs — 55% of the
English catalogue (every user-added word, and 583 pack words) carried NULL, so
nothing downstream could order or filter by difficulty. `freq_rank` is new:
1 = top-thousand common .. 5 = rare / narrow term.

Tagged offline in one batch (scripts/level_words.py) and keyed by
(track, normalized_word) — the table's unique key — so the data lands the same
way on any environment regardless of local id sequences.

Revision ID: 0037
Revises: 0036
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0037"
down_revision = "0036"
branch_labels = None
depends_on = None


# (normalized_word, level, freq_rank)
LEVELS: list[tuple[str, str, int]] = [
    ("a", "A1", 1),
    ("a table for two", "A2", 2),
    ("able", "A2", 1),
    ("about", "A1", 1),
    ("above", "A2", 1),
    ("abroad", "A2", 2),
    ("account", "B1", 2),
    ("acquire", "B2", 3),
    ("across", "A2", 1),
    ("act", "A1", 1),
    ("actually", "B1", 1),
    ("afraid", "A1", 1),
    ("after", "A1", 1),
    ("afternoon", "A1", 1),
    ("again", "A1", 1),
    ("against", "A2", 1),
    ("age", "A1", 1),
    ("ago", "A1", 1),
    ("ah", "A2", 2),
    ("ahead", "A2", 2),
    ("air", "A1", 1),
    ("airport", "A1", 2),
    ("all", "A1", 1),
    ("almost", "A2", 1),
    ("along", "A2", 1),
    ("already", "A2", 1),
    ("alright", "A2", 2),
    ("also", "A1", 1),
    ("although", "B1", 1),
    ("always", "A1", 1),
    ("am", "A1", 1),
    ("amaze", "B1", 2),
    ("amount", "A1", 1),
    ("an", "A1", 1),
    ("analyze", "B2", 2),
    ("and", "A1", 1),
    ("anger", "B1", 2),
    ("angry", "A1", 1),
    ("another", "A1", 1),
    ("anxious", "B1", 2),
    ("any", "A1", 1),
    ("anymore", "A2", 2),
    ("anyone", "A1", 1),
    ("anything", "A1", 1),
    ("anyway", "A2", 1),
    ("apartment", "A1", 1),
    ("app", "A1", 2),
    ("apparently", "B1", 2),
    ("appear", "A2", 1),
    ("apple", "A1", 1),
    ("approach", "B1", 2),
    ("approximately", "B2", 3),
    ("are", "A1", 1),
    ("area", "A1", 1),
    ("arm", "A1", 1),
    ("around", "A1", 1),
    ("arrival", "A2", 2),
    ("as", "A1", 1),
    ("aspect", "B2", 2),
    ("ass", "B1", 3),
    ("assist", "B1", 2),
    ("at", "A1", 1),
    ("attack", "A2", 2),
    ("attention", "A2", 1),
    ("aunt", "A1", 2),
    ("authority", "B1", 2),
    ("away", "A1", 1),
    ("baby", "A1", 1),
    ("back", "A1", 1),
    ("banana", "A1", 1),
    ("band", "A2", 2),
    ("bank", "A1", 1),
    ("bar", "A1", 2),
    ("barely", "B1", 3),
    ("basketball", "A1", 2),
    ("bathroom", "A1", 1),
    ("battery", "A2", 2),
    ("bear", "A1", 2),
    ("beat", "A2", 2),
    ("became", "A2", 1),
    ("because", "A1", 1),
    ("become", "A2", 1),
    ("bed", "A1", 1),
    ("bedroom", "A1", 1),
    ("been", "A1", 1),
    ("before", "A1", 1),
    ("began", "A2", 1),
    ("behind", "A2", 1),
    ("believe", "A1", 1),
    ("bell", "A2", 2),
    ("belt", "A2", 2),
    ("beside", "B1", 2),
    ("besides", "B1", 2),
    ("best", "A1", 1),
    ("better", "A1", 1),
    ("between", "A1", 1),
    ("bill", "A2", 2),
    ("bird", "A1", 2),
    ("bit", "A2", 1),
    ("black", "A1", 1),
    ("blanket", "A2", 2),
    ("blink", "A2", 3),
    ("block", "A1", 2),
    ("blockchain", "B2", 4),
    ("blonde", "A2", 3),
    ("blood", "A1", 2),
    ("blue", "A1", 1),
    ("blush", "B1", 3),
    ("boarding", "A2", 3),
    ("body", "A1", 1),
    ("boots", "A1", 2),
    ("bore", "A2", 3),
    ("bored", "A1", 2),
    ("boss", "A1", 2),
    ("both", "A1", 1),
    ("bottle", "A1", 2),
    ("bottom", "A2", 2),
    ("boy", "A1", 1),
    ("boyfriend", "A2", 2),
    ("brain", "A2", 2),
    ("branch", "B2", 4),
    ("bread", "A1", 1),
    ("break down", "B1", 2),
    ("breakfast", "A1", 1),
    ("breath", "A2", 2),
    ("breeze", "B1", 3),
    ("bridge", "A1", 2),
    ("broke", "A1", 2),
    ("broken", "A1", 2),
    ("brother", "A1", 1),
    ("brought", "A1", 2),
    ("brown", "A1", 2),
    ("brush", "A2", 2),
    ("budget", "B1", 2),
    ("bug", "A2", 3),
    ("build", "B1", 2),
    ("building", "A1", 1),
    ("burn", "A2", 2),
    ("burst", "B1", 3),
    ("bus", "A1", 2),
    ("business", "A1", 1),
    ("but", "A1", 1),
    ("butter", "A1", 1),
    ("button", "A1", 2),
    ("by", "A1", 1),
    ("calm", "A2", 2),
    ("came", "A1", 1),
    ("camping", "A2", 3),
    ("can", "A1", 1),
    ("can i get a discount?", "A2", 2),
    ("can i have a receipt?", "A2", 2),
    ("can i have the key?", "A1", 2),
    ("can i leave a message?", "A2", 2),
    ("can i leave my luggage here?", "A2", 3),
    ("can i pay by card?", "A2", 2),
    ("can i speak to...?", "A1", 1),
    ("can i try it on?", "A1", 2),
    ("can you call an ambulance?", "A2", 3),
    ("can you help me?", "A1", 1),
    ("can you show me on the map?", "A2", 2),
    ("can you speak up?", "B1", 3),
    ("card", "A1", 2),
    ("care", "A1", 1),
    ("carefully", "A2", 2),
    ("carpet", "A2", 2),
    ("case", "A1", 1),
    ("cash", "A2", 2),
    ("cat", "A1", 2),
    ("category", "B1", 2),
    ("caught", "A2", 2),
    ("ceiling", "A2", 2),
    ("cell", "B1", 2),
    ("chair", "A1", 1),
    ("chalkboard", "B1", 4),
    ("chance", "A1", 1),
    ("charger", "A2", 3),
    ("chase", "A2", 2),
    ("cheek", "A2", 2),
    ("cheese", "A1", 1),
    ("chess", "A2", 3),
    ("chest", "A2", 2),
    ("chicken", "A1", 1),
    ("children", "A1", 1),
    ("chuckle", "B1", 3),
    ("class", "A1", 1),
    ("classroom", "A1", 2),
    ("clear", "A1", 1),
    ("client", "A2", 2),
    ("cloud", "A1", 2),
    ("cloudy", "A1", 2),
    ("coach", "A2", 2),
    ("coat", "A1", 2),
    ("coffee", "A1", 1),
    ("colleague", "B1", 2),
    ("college", "A1", 1),
    ("color", "A1", 1),
    ("come back", "A1", 1),
    ("comment", "A2", 2),
    ("commit", "B2", 4),
    ("completely", "A2", 1),
    ("computer", "A1", 1),
    ("concept", "B1", 2),
    ("concern", "B1", 2),
    ("confuse", "A2", 2),
    ("confused", "A2", 2),
    ("consist", "B1", 2),
    ("constitute", "B2", 3),
    ("context", "B1", 2),
    ("contract", "B1", 2),
    ("contribute", "B2", 2),
    ("conversation", "A2", 2),
    ("coordinate", "B2", 3),
    ("corner", "A1", 2),
    ("cost", "A1", 1),
    ("couch", "A2", 3),
    ("cough", "A2", 3),
    ("could", "A1", 1),
    ("could i get a wake-up call?", "B1", 4),
    ("could you call me back?", "A2", 2),
    ("could you repeat that?", "A1", 1),
    ("counter", "A2", 2),
    ("couple", "A1", 1),
    ("course", "A1", 1),
    ("cousin", "A1", 2),
    ("cover", "A1", 1),
    ("cow", "A1", 2),
    ("crack", "A2", 2),
    ("criteria", "B2", 2),
    ("cross", "A1", 2),
    ("crossroads", "B1", 3),
    ("cup", "A1", 1),
    ("curious", "A2", 2),
    ("currency", "B1", 2),
    ("curtain", "A2", 2),
    ("customs", "B1", 3),
    ("cute", "A2", 2),
    ("cycling", "A2", 3),
    ("dad", "A1", 1),
    ("damn", "B1", 2),
    ("dancing", "A1", 2),
    ("data", "B1", 1),
    ("date", "A1", 1),
    ("daughter", "A1", 1),
    ("dead", "A1", 1),
    ("deadline", "B1", 3),
    ("dear", "A1", 2),
    ("death", "A1", 1),
    ("debt", "B1", 3),
    ("decline", "B1", 2),
    ("decrease", "B1", 2),
    ("definitely", "A2", 2),
    ("degree", "B1", 2),
    ("delay", "A2", 2),
    ("delicious", "A2", 2),
    ("demonstrate", "B1", 2),
    ("departure", "A2", 2),
    ("deploy", "B2", 4),
    ("desk", "A1", 2),
    ("device", "B1", 2),
    ("did", "A1", 1),
    ("die", "A1", 1),
    ("dinner", "A1", 1),
    ("dip", "B2", 3),
    ("diploma", "B1", 3),
    ("direction", "A2", 1),
    ("disappointed", "B1", 2),
    ("discount", "A2", 2),
    ("disease", "B1", 2),
    ("do you have a smaller one?", "A1", 2),
    ("do you have any rooms?", "A2", 3),
    ("do you have this in another size?", "A1", 2),
    ("do you speak english?", "A1", 1),
    ("do you take cards?", "A2", 2),
    ("doctor", "A1", 1),
    ("does", "A1", 1),
    ("dog", "A1", 1),
    ("dominate", "B2", 3),
    ("done", "A1", 1),
    ("down", "A1", 1),
    ("download", "A2", 2),
    ("drag", "B1", 2),
    ("dramatic", "B1", 2),
    ("draw", "A1", 1),
    ("drawer", "A2", 3),
    ("dress", "A1", 2),
    ("drop", "A2", 2),
    ("drove", "A2", 2),
    ("duck", "A1", 3),
    ("during", "A2", 1),
    ("each", "A1", 1),
    ("ear", "A1", 1),
    ("earn", "A2", 2),
    ("easily", "A2", 2),
    ("egg", "A1", 1),
    ("either", "A2", 1),
    ("elephant", "A1", 3),
    ("else", "A1", 1),
    ("embarrassed", "B1", 2),
    ("emphasis", "B2", 3),
    ("employee", "B1", 2),
    ("entire", "B1", 2),
    ("especially", "A2", 1),
    ("essay", "B1", 3),
    ("even", "A1", 1),
    ("evening", "A1", 1),
    ("eventually", "B1", 2),
    ("ever", "A1", 1),
    ("every", "A1", 1),
    ("everyone", "A1", 1),
    ("everything", "A1", 1),
    ("exactly", "A2", 2),
    ("exam", "A1", 2),
    ("except", "A2", 2),
    ("exchange", "B1", 2),
    ("excite", "B1", 3),
    ("excited", "A1", 2),
    ("exclaim", "B2", 4),
    ("excuse", "A2", 2),
    ("excuse me", "A1", 1),
    ("expense", "B1", 3),
    ("expression", "B1", 2),
    ("eye", "A1", 1),
    ("eyebrow", "B1", 3),
    ("face", "A1", 1),
    ("fare", "B1", 3),
    ("father", "A1", 1),
    ("favorite", "A2", 2),
    ("fear", "A2", 2),
    ("feet", "A1", 2),
    ("fell", "A2", 2),
    ("felt", "A1", 1),
    ("fever", "A2", 3),
    ("few", "A1", 1),
    ("fight", "A1", 1),
    ("figure", "A2", 1),
    ("figure out", "B1", 2),
    ("file", "A2", 2),
    ("finally", "A2", 1),
    ("find out", "A2", 2),
    ("fine", "A1", 1),
    ("finger", "A1", 1),
    ("fish", "A1", 1),
    ("fishing", "A2", 3),
    ("fit", "A2", 2),
    ("five", "A1", 1),
    ("flash", "B1", 3),
    ("flight", "A2", 2),
    ("flip", "B1", 3),
    ("floor", "A1", 1),
    ("fluctuate", "C1", 4),
    ("focus", "B1", 2),
    ("fog", "A2", 3),
    ("folder", "A2", 2),
    ("foot", "A1", 1),
    ("football", "A1", 2),
    ("for", "A1", 1),
    ("force", "B1", 2),
    ("forecast", "B1", 2),
    ("forget", "A1", 1),
    ("form", "A2", 2),
    ("forward", "A2", 2),
    ("found", "A1", 1),
    ("four", "A1", 1),
    ("fox", "A2", 3),
    ("freezing", "A2", 2),
    ("friday", "A1", 1),
    ("from", "A1", 1),
    ("front", "A1", 1),
    ("frown", "B1", 3),
    ("fruit", "A1", 1),
    ("fuck", "B1", 2),
    ("furniture", "A2", 2),
    ("further", "A2", 2),
    ("gasp", "B2", 3),
    ("gate", "A2", 2),
    ("gave", "A1", 1),
    ("gaze", "B2", 3),
    ("gently", "A2", 2),
    ("get up", "A1", 1),
    ("giggle", "B1", 3),
    ("girl", "A1", 1),
    ("girlfriend", "A2", 2),
    ("give up", "A2", 2),
    ("given", "A2", 1),
    ("glad", "A2", 2),
    ("glance", "B1", 2),
    ("glare", "B2", 3),
    ("gloves", "A2", 2),
    ("go on", "A1", 1),
    ("go straight", "A1", 2),
    ("go straight ahead", "A1", 2),
    ("god", "A1", 1),
    ("gold", "A2", 2),
    ("gone", "A1", 1),
    ("gonna", "A1", 1),
    ("got", "A1", 1),
    ("gotten", "A1", 1),
    ("grab", "A2", 2),
    ("grade", "A1", 2),
    ("gradual", "B2", 3),
    ("grandfather", "A1", 1),
    ("grandmother", "A1", 1),
    ("grape", "A2", 2),
    ("grateful", "B1", 2),
    ("great", "A1", 1),
    ("green", "A1", 1),
    ("grey", "A1", 2),
    ("grin", "B1", 3),
    ("grip", "B1", 3),
    ("groan", "B1", 3),
    ("grow up", "A2", 2),
    ("growth", "B1", 2),
    ("guard", "A2", 2),
    ("guess", "A1", 2),
    ("guitar", "A1", 2),
    ("gun", "A2", 2),
    ("guy", "A1", 1),
    ("gym", "A1", 2),
    ("had", "A1", 1),
    ("hair", "A1", 1),
    ("half", "A1", 1),
    ("hall", "A1", 2),
    ("hallway", "A2", 2),
    ("hand", "A1", 1),
    ("handle", "A2", 2),
    ("has", "A1", 1),
    ("hat", "A1", 2),
    ("having", "A1", 1),
    ("he", "A1", 1),
    ("he's not available right now", "B1", 2),
    ("head", "A1", 1),
    ("headache", "A2", 3),
    ("health", "A1", 1),
    ("healthy", "A1", 1),
    ("heard", "A1", 1),
    ("heart", "A1", 1),
    ("hell", "A2", 2),
    ("her", "A1", 1),
    ("herself", "A2", 2),
    ("hey", "A1", 2),
    ("hi", "A1", 1),
    ("hide", "A1", 2),
    ("hiking", "A2", 3),
    ("him", "A1", 1),
    ("himself", "A2", 2),
    ("hire", "B1", 2),
    ("his", "A1", 1),
    ("hobby", "A1", 2),
    ("hold on, please", "A1", 2),
    ("holding", "A1", 1),
    ("homework", "A1", 2),
    ("horrible", "A2", 2),
    ("horse", "A1", 2),
    ("hospital", "A1", 1),
    ("hotel", "A1", 1),
    ("how", "A1", 1),
    ("how are you?", "A1", 1),
    ("how do i get to...?", "A1", 1),
    ("how long does it take?", "A1", 1),
    ("how much does it cost?", "A1", 1),
    ("how much is it?", "A1", 1),
    ("how often should i take this?", "A2", 3),
    ("however", "A2", 1),
    ("hug", "A2", 2),
    ("human", "A2", 2),
    ("humid", "B1", 3),
    ("hundred", "A1", 1),
    ("hung", "A2", 2),
    ("husband", "A1", 1),
    ("i", "A1", 1),
    ("i can't hear you well", "A1", 2),
    ("i don't feel well", "A1", 2),
    ("i don't understand", "A1", 1),
    ("i feel dizzy", "B1", 4),
    ("i have a booking", "A2", 3),
    ("i have a fever", "A2", 3),
    ("i have a headache", "A2", 3),
    ("i have a reservation", "B1", 2),
    ("i have a sore throat", "A2", 3),
    ("i need a doctor", "A1", 2),
    ("i think i'm lost", "A2", 2),
    ("i'd like a double room", "A2", 3),
    ("i'd like to check in", "B1", 2),
    ("i'd like to check out", "A2", 3),
    ("i'd like to order", "A2", 2),
    ("i'll take it", "A1", 1),
    ("i'm a vegetarian", "B1", 3),
    ("i'm allergic to nuts", "B1", 3),
    ("i'm allergic to penicillin", "B1", 4),
    ("i'm just looking", "A1", 1),
    ("i'm lost", "A2", 2),
    ("i'm sorry", "A1", 1),
    ("i've caught a cold", "A2", 3),
    ("ice", "A1", 2),
    ("if", "A1", 1),
    ("ill", "A2", 2),
    ("illness", "A2", 2),
    ("immediately", "B1", 2),
    ("implement", "B2", 3),
    ("imply", "B2", 3),
    ("impossible", "A2", 2),
    ("in", "A1", 1),
    ("inch", "A2", 3),
    ("income", "B1", 3),
    ("indeed", "B1", 2),
    ("initial", "B2", 2),
    ("injury", "B1", 3),
    ("inside", "A1", 2),
    ("instance", "B2", 3),
    ("instead", "A2", 2),
    ("interest", "A1", 1),
    ("internet", "A1", 1),
    ("interpret", "B2", 3),
    ("interview", "A2", 2),
    ("into", "A1", 1),
    ("invade", "B2", 4),
    ("invest", "B1", 3),
    ("invisible", "B1", 3),
    ("is", "A1", 1),
    ("is breakfast included?", "A2", 3),
    ("is it far from here?", "A1", 2),
    ("is it on sale?", "A2", 2),
    ("is it spicy?", "A2", 3),
    ("is this seat taken?", "A2", 2),
    ("is this the right way?", "A1", 2),
    ("it", "A1", 1),
    ("it depends", "A2", 1),
    ("it hurts here", "A1", 2),
    ("it's", "A1", 1),
    ("it's across the street", "A2", 2),
    ("it's around the corner", "A2", 2),
    ("it's delicious", "A2", 2),
    ("it's next to the bank", "A1", 2),
    ("it's too expensive", "A1", 2),
    ("its", "A1", 1),
    ("itself", "A2", 2),
    ("jacket", "A1", 2),
    ("jail", "A2", 3),
    ("jealous", "A2", 2),
    ("jeans", "A1", 2),
    ("joke", "A1", 2),
    ("journey", "A2", 2),
    ("juice", "A1", 2),
    ("just", "A1", 1),
    ("kept", "A2", 2),
    ("keyboard", "A1", 2),
    ("kid", "A1", 2),
    ("kill", "A1", 2),
    ("killed", "A2", 2),
    ("king", "A1", 2),
    ("kiss", "A1", 2),
    ("kitchen", "A1", 2),
    ("knee", "A2", 3),
    ("knew", "A1", 2),
    ("knife", "A2", 3),
    ("known", "A2", 2),
    ("lady", "A1", 2),
    ("laid", "A2", 3),
    ("lamp", "A1", 2),
    ("land", "A1", 1),
    ("language", "A1", 1),
    ("laptop", "A1", 2),
    ("large", "A1", 1),
    ("later", "A1", 1),
    ("law", "A1", 1),
    ("lay", "A2", 1),
    ("leader", "A2", 1),
    ("least", "A2", 1),
    ("lecture", "B1", 3),
    ("ledger", "B2", 4),
    ("left", "A1", 1),
    ("leg", "A1", 1),
    ("less", "A1", 1),
    ("lesson", "A1", 2),
    ("let me call you back", "A2", 2),
    ("library", "A1", 2),
    ("lie", "A2", 1),
    ("life", "A1", 1),
    ("lift", "A2", 1),
    ("lightning", "A2", 3),
    ("lion", "A1", 3),
    ("lip", "A2", 2),
    ("loan", "B1", 3),
    ("lonely", "A2", 2),
    ("look after", "A2", 2),
    ("look for", "A2", 2),
    ("look forward to", "B1", 2),
    ("lost", "A1", 1),
    ("luggage", "A2", 3),
    ("lunch", "A1", 2),
    ("machine", "A2", 1),
    ("mad", "A2", 2),
    ("magic", "A2", 2),
    ("main", "A2", 1),
    ("manager", "A1", 1),
    ("many", "A1", 1),
    ("map", "A1", 2),
    ("match", "A2", 1),
    ("maybe", "A1", 1),
    ("mean", "A1", 1),
    ("meant", "A1", 1),
    ("meat", "A1", 1),
    ("medicine", "A1", 2),
    ("meeting", "A1", 1),
    ("memory", "A2", 1),
    ("merge", "B2", 4),
    ("message", "A2", 1),
    ("might", "A2", 1),
    ("mild", "B1", 3),
    ("mile", "A2", 2),
    ("milk", "A1", 2),
    ("mind", "A2", 1),
    ("mine", "A1", 2),
    ("miner", "B2", 4),
    ("minimize", "B2", 3),
    ("minute", "A1", 1),
    ("mirror", "A2", 2),
    ("miss", "A1", 1),
    ("mistake", "A1", 1),
    ("moment", "A1", 1),
    ("monday", "A1", 2),
    ("money", "A1", 1),
    ("monkey", "A1", 2),
    ("moon", "A1", 2),
    ("more", "A1", 1),
    ("most", "A1", 1),
    ("mother", "A1", 1),
    ("mouse", "A1", 2),
    ("mouth", "A1", 2),
    ("movie", "A1", 2),
    ("much", "A1", 1),
    ("murder", "B1", 2),
    ("must", "A1", 1),
    ("my", "A1", 1),
    ("my battery is dying", "B1", 3),
    ("myself", "A1", 2),
    ("nation", "A2", 2),
    ("natural", "A2", 2),
    ("nearly", "A2", 2),
    ("neck", "A2", 2),
    ("needed", "A1", 1),
    ("neighbor", "A1", 2),
    ("neither", "B1", 2),
    ("nervous", "A2", 2),
    ("network", "B1", 2),
    ("never", "A1", 1),
    ("never mind", "A2", 2),
    ("news", "A1", 1),
    ("nice to meet you", "A1", 1),
    ("nine", "A1", 2),
    ("no", "A1", 1),
    ("no ice, please", "A2", 3),
    ("no problem", "A1", 1),
    ("nobody", "A1", 2),
    ("nod", "B1", 3),
    ("none", "B1", 2),
    ("noon", "A2", 3),
    ("nor", "B1", 2),
    ("north", "A1", 2),
    ("nose", "A1", 2),
    ("not", "A1", 1),
    ("notebook", "A1", 2),
    ("nothing", "A1", 1),
    ("nurse", "A1", 2),
    ("objective", "B1", 2),
    ("obtain", "B2", 3),
    ("obviously", "B1", 2),
    ("occupy", "B1", 2),
    ("ocean", "A2", 2),
    ("of", "A1", 1),
    ("of course", "A1", 1),
    ("off", "A1", 1),
    ("office", "A1", 1),
    ("often", "A1", 1),
    ("oh", "A1", 1),
    ("oil", "A1", 2),
    ("okay", "A1", 1),
    ("on", "A1", 1),
    ("once", "A1", 1),
    ("one", "A1", 1),
    ("one ticket, please", "A1", 2),
    ("onion", "A1", 2),
    ("only", "A1", 1),
    ("opening", "A2", 2),
    ("opposite", "A2", 2),
    ("option", "B1", 2),
    ("or", "A1", 1),
    ("orange", "A1", 2),
    ("other", "A1", 1),
    ("our", "A1", 1),
    ("ourselves", "A2", 2),
    ("out", "A1", 1),
    ("outside", "A1", 2),
    ("over", "A1", 1),
    ("pain", "A2", 2),
    ("painting", "A1", 2),
    ("pair", "A2", 2),
    ("paper", "A1", 2),
    ("parent", "A1", 2),
    ("park", "A1", 2),
    ("part", "A1", 1),
    ("partner", "A2", 2),
    ("pass", "A2", 2),
    ("passport", "A1", 2),
    ("password", "A1", 2),
    ("past", "A2", 2),
    ("path", "A2", 2),
    ("patient", "B1", 2),
    ("peak", "B1", 2),
    ("pencil", "A1", 2),
    ("perceive", "B2", 3),
    ("perhaps", "B1", 2),
    ("period", "B1", 2),
    ("person", "A1", 1),
    ("personal", "B1", 2),
    ("pharmacy", "A2", 3),
    ("phone", "A1", 1),
    ("photo", "A1", 2),
    ("pick up", "A2", 1),
    ("pig", "A1", 3),
    ("pink", "A1", 2),
    ("plane", "A1", 2),
    ("plastic", "A2", 2),
    ("plateau", "C1", 4),
    ("platform", "A2", 2),
    ("player", "A2", 2),
    ("please", "A1", 1),
    ("pleasure", "B1", 2),
    ("plummet", "C1", 4),
    ("pocket", "A1", 2),
    ("point", "A1", 1),
    ("police", "A1", 1),
    ("policy", "B1", 1),
    ("position", "A2", 1),
    ("post", "A1", 1),
    ("potato", "A1", 2),
    ("potential", "B1", 2),
    ("pound", "A2", 2),
    ("practice", "A2", 2),
    ("present", "A1", 1),
    ("president", "A2", 1),
    ("pretty", "A1", 1),
    ("price", "A1", 1),
    ("primary", "B1", 2),
    ("prince", "A2", 2),
    ("princess", "A2", 2),
    ("principle", "B1", 2),
    ("print", "A2", 2),
    ("prior", "B2", 3),
    ("prison", "A2", 2),
    ("probably", "A2", 1),
    ("procedure", "B1", 2),
    ("produce", "B1", 1),
    ("product", "A2", 1),
    ("profession", "B1", 2),
    ("profit", "B1", 2),
    ("program", "A2", 1),
    ("project", "A2", 1),
    ("promote", "B1", 2),
    ("promotion", "B1", 3),
    ("proportion", "B2", 3),
    ("proud", "B1", 2),
    ("publish", "B1", 2),
    ("punish", "B1", 3),
    ("pupil", "A2", 3),
    ("purple", "A1", 2),
    ("put on", "A1", 1),
    ("quarter", "A2", 2),
    ("queen", "A2", 2),
    ("quick", "A1", 2),
    ("quickly", "A1", 1),
    ("quit", "B1", 2),
    ("quite", "A2", 1),
    ("rabbit", "A1", 3),
    ("race", "A2", 2),
    ("radio", "A1", 2),
    ("rain", "A1", 1),
    ("rainbow", "A2", 3),
    ("ran", "A1", 1),
    ("rate", "B1", 2),
    ("rather", "B1", 1),
    ("reach", "A2", 1),
    ("really", "A1", 1),
    ("record", "A2", 1),
    ("recover", "B1", 2),
    ("red", "A1", 1),
    ("region", "B1", 2),
    ("register", "B1", 2),
    ("regulate", "B2", 3),
    ("relation", "B1", 2),
    ("relative", "A2", 2),
    ("release", "B1", 2),
    ("relieved", "B1", 3),
    ("remain", "B1", 2),
    ("remember", "A1", 1),
    ("reply", "A2", 2),
    ("report", "A2", 2),
    ("research", "B1", 1),
    ("reservation", "B1", 2),
    ("respectively", "C1", 4),
    ("responsible", "B1", 2),
    ("restrict", "B2", 3),
    ("resume", "B1", 3),
    ("revenue", "B2", 3),
    ("review", "B1", 3),
    ("rice", "A1", 3),
    ("rich", "A1", 2),
    ("ring", "A1", 2),
    ("rise", "A2", 2),
    ("road", "A1", 1),
    ("rock", "A2", 2),
    ("roll", "A2", 3),
    ("root", "B1", 3),
    ("rope", "A2", 3),
    ("rose", "A2", 3),
    ("round", "A1", 2),
    ("row", "A2", 3),
    ("rub", "B1", 3),
    ("rule", "A2", 2),
    ("run out", "B1", 2),
    ("running", "A1", 2),
    ("sad", "A1", 2),
    ("said", "A1", 1),
    ("salad", "A1", 1),
    ("salary", "B1", 2),
    ("salt", "A2", 3),
    ("sat", "A1", 2),
    ("satisfy", "B2", 3),
    ("saturday", "A1", 1),
    ("save", "A1", 1),
    ("saw", "A1", 2),
    ("say", "A1", 1),
    ("scale", "B1", 3),
    ("scarf", "A2", 2),
    ("schedule", "A2", 2),
    ("science", "A2", 2),
    ("scissors", "A2", 3),
    ("score", "A2", 2),
    ("screen", "A1", 2),
    ("season", "A1", 2),
    ("seat", "A2", 2),
    ("second", "A1", 1),
    ("secret", "A2", 2),
    ("section", "B1", 2),
    ("sector", "B1", 2),
    ("see you later", "A1", 1),
    ("sell", "A1", 2),
    ("semester", "B1", 3),
    ("sense", "B1", 2),
    ("sentence", "A2", 2),
    ("separate", "B1", 2),
    ("sequence", "B2", 3),
    ("set", "A1", 1),
    ("set up", "B1", 2),
    ("seven", "A1", 1),
    ("several", "A2", 1),
    ("shall", "A2", 1),
    ("sharp", "A2", 2),
    ("she", "A1", 1),
    ("sheep", "A1", 2),
    ("sheet", "A2", 2),
    ("shelf", "A2", 2),
    ("shift", "B1", 2),
    ("shine", "A2", 2),
    ("ship", "B1", 2),
    ("shirt", "A1", 2),
    ("shock", "A2", 2),
    ("shoe", "A1", 1),
    ("shoes", "A1", 1),
    ("shoot", "A2", 2),
    ("should", "A1", 1),
    ("shoulder", "A2", 2),
    ("show up", "B1", 2),
    ("sick", "A1", 2),
    ("sidewalk", "A2", 3),
    ("sight", "B1", 2),
    ("signpost", "B2", 4),
    ("silver", "A2", 2),
    ("simple", "A1", 1),
    ("since", "A2", 1),
    ("sister", "A1", 1),
    ("six", "A1", 1),
    ("skill", "B1", 2),
    ("skin", "A2", 2),
    ("skirt", "A1", 2),
    ("sleeve", "A2", 3),
    ("slight", "B1", 2),
    ("slip", "B1", 2),
    ("smoke", "A1", 2),
    ("snake", "A1", 2),
    ("snow", "A1", 2),
    ("so", "A1", 1),
    ("soap", "A2", 2),
    ("soar", "C1", 4),
    ("socks", "A1", 2),
    ("sofa", "A1", 2),
    ("software", "B1", 2),
    ("soil", "B1", 3),
    ("some", "A1", 1),
    ("son", "A1", 2),
    ("soon", "A1", 1),
    ("sorry", "A1", 1),
    ("sounds good", "A2", 2),
    ("soup", "A1", 1),
    ("south", "A1", 2),
    ("souvenir", "A2", 3),
    ("space", "A2", 1),
    ("special", "A1", 1),
    ("speech", "B1", 2),
    ("spell", "A2", 2),
    ("spoon", "A2", 3),
    ("sport", "A1", 1),
    ("spring", "A1", 1),
    ("square", "A1", 1),
    ("stage", "A2", 1),
    ("stairs", "A1", 2),
    ("stake", "B2", 4),
    ("stakeholder", "B2", 4),
    ("star", "A1", 1),
    ("state", "A2", 1),
    ("station", "A1", 1),
    ("stay", "A1", 1),
    ("steady", "B1", 2),
    ("steam", "B1", 2),
    ("step", "A1", 1),
    ("stick", "A2", 2),
    ("still", "A1", 1),
    ("stomach", "A2", 2),
    ("store", "A1", 1),
    ("storm", "A2", 2),
    ("straight", "A2", 2),
    ("strange", "A1", 1),
    ("strategy", "B1", 2),
    ("street", "A1", 1),
    ("student", "A1", 1),
    ("study", "A1", 1),
    ("subject", "A2", 1),
    ("substantial", "B2", 3),
    ("subway", "A2", 2),
    ("such", "A1", 1),
    ("sufficient", "B2", 2),
    ("sugar", "A1", 2),
    ("suit", "A2", 2),
    ("suitcase", "A2", 3),
    ("summary", "B1", 2),
    ("summer", "A1", 1),
    ("sun", "A1", 1),
    ("sunday", "A1", 2),
    ("sunny", "A1", 2),
    ("supper", "B1", 3),
    ("surface", "B1", 2),
    ("surge", "B2", 3),
    ("surprised", "A1", 2),
    ("survey", "B1", 2),
    ("sustain", "B2", 3),
    ("sweater", "A1", 2),
    ("swimming", "A1", 2),
    ("system", "A2", 1),
    ("table", "A1", 1),
    ("take care", "A2", 2),
    ("take off", "A1", 1),
    ("task", "A2", 2),
    ("tax", "B1", 2),
    ("taxi", "A1", 2),
    ("tea", "A1", 1),
    ("teacher", "A1", 1),
    ("team", "A1", 1),
    ("tear", "B1", 2),
    ("technique", "B1", 2),
    ("telephone", "A1", 2),
    ("television", "A1", 2),
    ("temperature", "A2", 2),
    ("ten", "A1", 1),
    ("tennis", "A1", 2),
    ("term", "B1", 2),
    ("test", "A1", 2),
    ("text", "A1", 2),
    ("than", "A1", 1),
    ("thank", "A1", 1),
    ("that", "A1", 1),
    ("the", "A1", 1),
    ("the bill, please", "A2", 2),
    ("the line is busy", "A2", 2),
    ("the menu, please", "A1", 2),
    ("the room is too cold", "A1", 2),
    ("the wi-fi isn't working", "A1", 2),
    ("their", "A1", 1),
    ("them", "A1", 1),
    ("then", "A1", 1),
    ("theory", "B1", 2),
    ("there", "A1", 1),
    ("these", "A1", 1),
    ("they", "A1", 1),
    ("thing", "A1", 1),
    ("third", "A1", 2),
    ("this", "A1", 1),
    ("those", "A1", 1),
    ("though", "B1", 1),
    ("thought", "A1", 1),
    ("thousand", "A2", 2),
    ("three", "A1", 1),
    ("through", "A2", 1),
    ("thunder", "A2", 3),
    ("thursday", "A1", 2),
    ("ticket", "A1", 2),
    ("tie", "A2", 2),
    ("tiger", "A1", 3),
    ("title", "A2", 2),
    ("to", "A1", 1),
    ("together", "A1", 1),
    ("token", "B2", 4),
    ("tomato", "A1", 2),
    ("tomorrow", "A1", 2),
    ("tonight", "A1", 2),
    ("too", "A1", 1),
    ("tool", "A2", 2),
    ("tooth", "A2", 2),
    ("top", "A1", 1),
    ("total", "B1", 2),
    ("tourist", "A2", 2),
    ("toward", "B1", 2),
    ("track", "A2", 2),
    ("trade", "A2", 2),
    ("traffic", "A1", 2),
    ("train", "A1", 2),
    ("transfer", "B1", 2),
    ("transform", "B2", 3),
    ("treatment", "B1", 2),
    ("trend", "B1", 2),
    ("trip", "A1", 2),
    ("trouble", "A2", 2),
    ("trousers", "A1", 2),
    ("tuesday", "A1", 2),
    ("turn left", "A1", 2),
    ("turn left at the corner", "A1", 2),
    ("turn off", "A1", 1),
    ("turn on", "A1", 1),
    ("turn right", "A1", 2),
    ("twelve", "A1", 2),
    ("twenty", "A1", 2),
    ("two", "A1", 1),
    ("type", "A2", 2),
    ("ultimate", "B2", 2),
    ("uncle", "A1", 2),
    ("under", "A1", 1),
    ("understand", "A1", 1),
    ("undertake", "B2", 3),
    ("unit", "A2", 2),
    ("universe", "B1", 2),
    ("university", "A1", 2),
    ("until", "A1", 1),
    ("up", "A1", 1),
    ("update", "A2", 2),
    ("upload", "A2", 2),
    ("upon", "B1", 2),
    ("utilize", "B2", 3),
    ("vacation", "A1", 2),
    ("vary", "B2", 3),
    ("vegetable", "A1", 1),
    ("version", "A2", 2),
    ("very", "A1", 1),
    ("via", "B2", 2),
    ("volume", "B1", 2),
    ("wake up", "A1", 1),
    ("wall", "A1", 1),
    ("wallet", "A2", 2),
    ("water, please", "A1", 1),
    ("way", "A1", 1),
    ("weather", "A1", 2),
    ("website", "A1", 2),
    ("wednesday", "A1", 2),
    ("welcome", "A1", 2),
    ("welfare", "B2", 3),
    ("well", "A1", 1),
    ("west", "A1", 2),
    ("what", "A1", 1),
    ("what do you mean?", "A1", 1),
    ("what do you recommend?", "B1", 2),
    ("what time is check-out?", "A2", 3),
    ("what time is the flight?", "A2", 2),
    ("what's up?", "A2", 2),
    ("when", "A1", 1),
    ("where", "A1", 1),
    ("where is the bathroom?", "A1", 1),
    ("where is the elevator?", "A1", 2),
    ("where is the fitting room?", "A2", 2),
    ("where is the gate?", "A2", 2),
    ("where is the nearest metro?", "A2", 2),
    ("where is the nearest pharmacy?", "A2", 3),
    ("whereas", "B2", 3),
    ("which", "A1", 1),
    ("while", "A2", 1),
    ("white", "A1", 1),
    ("who", "A1", 1),
    ("who's calling?", "A1", 2),
    ("why", "A1", 1),
    ("wife", "A1", 2),
    ("will", "A1", 1),
    ("wind", "A1", 2),
    ("window", "A1", 1),
    ("windy", "A1", 2),
    ("wine", "A1", 2),
    ("winter", "A1", 2),
    ("with", "A1", 1),
    ("wolf", "A2", 3),
    ("wood", "A1", 2),
    ("yellow", "A1", 2),
    ("yes", "A1", 1),
    ("yesterday", "A1", 2),
    ("yet", "A2", 1),
    ("yield", "B2", 3),
    ("you", "A1", 1),
    ("you're welcome", "A1", 1),
    ("you've got the wrong number", "A2", 2),
    ("your", "A1", 1),
    ("yourself", "A2", 2),
]


def upgrade() -> None:
    op.add_column("words", sa.Column("freq_rank", sa.Integer(), nullable=True))

    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET level = :level, freq_rank = :freq "
        "WHERE track = 'en' AND normalized_word = :n AND level IS NULL"
    )
    for n, level, freq in LEVELS:
        conn.execute(stmt, {"n": n, "level": level, "freq": freq})


def downgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET level = NULL WHERE track = 'en' AND normalized_word = :n"
    )
    for n, _level, _freq in LEVELS:
        conn.execute(stmt, {"n": n})
    op.drop_column("words", "freq_rank")
