"""Example sentences and context hints for the words that had neither.

A word without an example cannot show a cloze card, and mastery now requires
typed answers — so until this landed, 639 words could not be learned at all.
The hint (abstract_example_en/ru) describes the situation around the word
without naming it, giving context on the push card without handing over the
answer; it existed on 16 words out of 2046.

Generated offline by scripts/gen_examples.py and machine-checked before being
written here: the sentence contains the word in the form the bot's masker
actually accepts, at least three words survive the blanking, the hint never
contains the word, and neither uses vocabulary rated above the word's own level
in our catalogue. 432 candidates were rejected and regenerated; 98 phrasebook
entries are absent on purpose, being whole sentences with nowhere to blank.

Keyed by (track, normalized_word), and every column is written only where it is
still empty, so a hand-written example is never overwritten.

Revision ID: 0041
Revises: 0040
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0041"
down_revision = "0040"
branch_labels = None
depends_on = None


# (normalized_word, example_sentence, hint_en, hint_ru)
EXAMPLES: list[tuple[str, str, str, str]] = [
    ("a table for two", "We need a table for two people.", "We want a place to eat for a couple.", "Мы хотим место, чтобы поесть для пары."),
    ("able", "He is able to run very fast in the park.", "He can run very fast in the park.", "Он может очень быстро бегать в парке."),
    ("about", "We talk about the new film today.", "We speak of the new film today.", "Мы говорим на тему нового фильма сегодня."),
    ("above", "The bird flies above the tall trees.", "The bird is in the sky over the tall trees.", "Птица в небе над высокими деревьями."),
    ("across", "They walk across the small green park.", "They go from one side of the park to the other side.", "Они идут с одного края парка на другой."),
    ("act", "Please act now to help your friend.", "Please do something now to help your friend.", "Пожалуйста, сделай что-нибудь сейчас, чтобы помочь другу."),
    ("actually", "I am actually very happy right now.", "In truth, I am very happy right now.", "По правде говоря, я сейчас очень счастлив."),
    ("add", "Please add some milk to my coffee.", "Please put some more milk into my coffee.", "Пожалуйста, положи еще немного молока в мой кофе."),
    ("after", "We eat dinner after the long school day.", "We eat dinner when the school day is finished.", "Мы ужинаем, когда школьный день закончен."),
    ("again", "Please say the word again for me.", "Please say the word one more time for me.", "Пожалуйста, произнеси слово еще разок для меня."),
    ("against", "They play football against the other team.", "They play football in a game with the other team.", "Они играют в футбол в матче против другой команды."),
    ("age", "What is your age, my young friend?", "How many years old are you, my friend?", "Сколько тебе лет, мой друг?"),
    ("ago", "I saw him two days ago at school.", "I saw him two days before now at school.", "Я видел его два дня назад в школе."),
    ("ah", "Ah, now I understand your new plan.", "Oh, I see your new plan now.", "О, теперь я понимаю твой новый план."),
    ("ahead", "The road ahead is very long today.", "The road in front of us is very long today.", "Дорога перед нами очень длинная сегодня."),
    ("air", "The air is very clean in the mountains.", "The wind and the sky are very clean in the mountains.", "Ветер и небо очень чистые в горах."),
    ("all", "All the students are here in class.", "Every student is here in class.", "Каждый ученик сейчас здесь в классе."),
    ("almost", "I am almost ready to go home now.", "I am nearly ready to go home now.", "Я почти готов идти домой сейчас."),
    ("along", "We walk along the beach in the sun.", "We walk by the side of the beach in the sun.", "Мы гуляем вдоль пляжа на солнце."),
    ("already", "I have already finished my hard work.", "I finished my hard work before this moment.", "Я закончил свою тяжелую работу до этого момента."),
    ("alright", "Everything is alright with my new car.", "Everything is fine and good with my new car.", "Все хорошо с моей новой машиной."),
    ("also", "I like tea and I also like coffee.", "I like tea and I like coffee too.", "Мне нравится чай, и кофе мне тоже нравится."),
    ("although", "I went out although it was raining.", "It was raining but I went out.", "Шел дождь, но я все равно вышел на улицу."),
    ("am", "I am a teacher at this school.", "My job is to teach at this school.", "Моя работа — преподавать в этой школе."),
    ("amaze", "The big magic show will amaze you.", "The magic show will make you feel surprised.", "Это магическое шоу очень тебя удивит."),
    ("and", "I have a pen and a book.", "I have a pen plus a book.", "У меня есть ручка в дополнение к книге."),
    ("anger", "He felt great anger after the fight.", "He felt very mad after the fight.", "Он был очень зол после драки."),
    ("annoy", "Loud music can annoy my cat.", "Loud music makes my cat feel bad.", "Громкая музыка заставляет кота нервничать."),
    ("another", "I need another cup of tea.", "I need one more cup of tea.", "Мне нужна еще одна чашка чая."),
    ("anymore", "He does not live here anymore.", "He stopped living here in the past.", "Он перестал здесь жить."),
    ("anyone", "Can anyone help me with this bag?", "Is there a person who can help me?", "Есть ли кто-то, кто может помочь мне с сумкой?"),
    ("anything", "Do you want anything to eat?", "Do you want some food?", "Хочешь что-нибудь поесть?"),
    ("anyway", "Anyway, let us go home now.", "In any case, let us go home now.", "В любом случае, давай пойдем домой сейчас."),
    ("apartment", "They live in a small apartment.", "They live in a small flat in a big building.", "Они живут в небольшой квартире в большом доме."),
    ("apparently", "Apparently, the store is closed today.", "It seems that the store is closed today.", "По всей видимости, магазин сегодня закрыт."),
    ("appear", "Stars appear in the sky at night.", "Stars show up in the sky at night.", "Звезды становятся видны на небе по ночам."),
    ("are", "We are happy to see you.", "We feel happy seeing you.", "Мы рады тебя видеть."),
    ("area", "This is a nice area to live.", "This is a good place to live.", "Это хороший район для жизни."),
    ("around", "They walk around the big park every day.", "They move in a circle near the big place.", "Они ходят по кругу рядом с этим большим местом."),
    ("as", "Do as I say now.", "Follow my instructions.", "Делай так, как я говорю."),
    ("ass", "He fell down on his ass.", "He hit his bottom on the ground.", "Он упал на свою пятую точку."),
    ("at", "I am at home today.", "I am inside the house right now.", "Я сейчас дома."),
    ("attack", "The dog will attack the cat.", "The dog wants to fight the cat.", "Собака собирается наброситься на кошку."),
    ("attention", "Please pay attention to the teacher.", "Please look and listen to the teacher.", "Пожалуйста, будь внимателен к учителю."),
    ("away", "Please go away and let me sleep now.", "Leave this place and do not come back here.", "Уйди отсюда и не возвращайся."),
    ("baby", "The baby is sleeping in the bed.", "The very young child is sleeping.", "Малыш спит в кроватке."),
    ("bag", "Put your book in the bag.", "Put your book inside your carry case.", "Положи свою книгу в сумку."),
    ("ball", "The boy plays with a red ball.", "He plays with a round toy.", "Мальчик играет с красным мячом."),
    ("band", "They have a music band.", "They have a group that plays music.", "У них есть музыкальная группа."),
    ("bar", "Let us meet at the bar.", "Let us meet at the place that sells drinks.", "Давай встретимся в баре."),
    ("barely", "I can barely hear your voice.", "It is very hard to hear you.", "Я почти не слышу твой голос."),
    ("be", "I want to be a doctor one day.", "I want to work as a doctor in the future.", "Я хочу работать врачом в будущем."),
    ("beat", "My heart beat very fast.", "My heart moved quickly inside my chest.", "Мое сердце бешено колотилось."),
    ("became", "He became a doctor last year.", "He started to work as a doctor.", "Он стал врачом в прошлом году."),
    ("become", "Do you want to become a teacher?", "Do you want to be a teacher later?", "Ты хочешь стать учителем?"),
    ("been", "I have been to Paris twice.", "I visited that city two times.", "Я был в Париже дважды."),
    ("before", "Wash your hands before you eat dinner.", "Do this action at an earlier time than your meal.", "Сделай это действие раньше, чем начнешь ужинать."),
    ("began", "He began his work at nine.", "He started his work at nine.", "Он начал свою работу в девять."),
    ("begin", "The movie will begin at seven o'clock tonight.", "The film starts at seven this evening.", "Фильм начинается сегодня вечером в семь."),
    ("behind", "My house is behind the big park.", "My home is at the back of the park.", "Мой дом находится с обратной стороны парка."),
    ("believe", "I believe that you are a good person.", "I think you are a good person and it is true.", "Я думаю, что ты хороший человек, и это правда."),
    ("bell", "Please ring the bell at the front door.", "Press the button to make a sound at the door.", "Нажми кнопку, чтобы раздался звук у двери."),
    ("beside", "He sits beside me in the classroom.", "He sits next to me in class.", "Он сидит рядом со мной в классе."),
    ("besides", "Besides coffee, I like to drink tea.", "In addition to coffee, I also like tea.", "В дополнение к кофе, я также люблю чай."),
    ("best", "She is my best friend in school.", "She is the number one friend I have.", "Она мой самый близкий друг в школе."),
    ("better", "This book is better than that one.", "This book is more good than the other one.", "Эта книга более хорошая, чем та."),
    ("bit", "Can I have a little bit of cake?", "Can I have a small piece of cake?", "Можно мне маленький кусочек торта?"),
    ("blink", "You blink when the light is very bright.", "You close and open your eyes quickly.", "Ты быстро закрываешь и открываешь глаза."),
    ("block", "I walk one block to get to school.", "It is a part of a city with four streets around it.", "Это часть города, окруженная четырьмя улицами."),
    ("blonde", "She has long blonde hair.", "She has light yellow hair.", "У неё светлые волосы."),
    ("blush", "She starts to blush when he looks at her.", "Her face becomes red because she is shy.", "Ее лицо становится красным, потому что она стесняется."),
    ("body", "He takes good care of his body.", "It is all of you from your head to your feet.", "Это всё, что есть у тебя от головы до пят."),
    ("bore", "Long lessons bore me every day.", "Long lessons are not interesting for me.", "Длинные уроки мне не интересны."),
    ("both", "Both of them are my brothers.", "The two people are my brothers.", "Эти двое — мои братья."),
    ("bottle", "I need a bottle of cold water.", "I need a glass container for water.", "Мне нужна стеклянная или пластиковая емкость для воды."),
    ("bottom", "Look at the bottom of the cup.", "Look at the lowest part of the cup.", "Посмотри на самую нижнюю часть чашки."),
    ("box", "Put the toys in the box.", "Put the toys in the square container.", "Положи игрушки в квадратную емкость."),
    ("boy", "The small boy plays in the park.", "A young male child is playing outside.", "Маленький ребенок мужского пола играет на улице."),
    ("boyfriend", "She walks with her boyfriend in the park.", "She is with the man she loves.", "Она гуляет с любимым человеком."),
    ("break", "Let us take a short break now.", "We should stop our work for a little time.", "Нам стоит ненадолго остановить работу."),
    ("break down", "My old car will break down on the long road.", "My car will stop working because it is very old.", "Моя старая машина сломается в долгой дороге."),
    ("breathe", "It is hard to breathe in this room.", "I cannot get enough air into my lungs.", "Я не могу вдохнуть достаточно воздуха."),
    ("bring", "Please bring me a glass of water.", "Can you carry a drink to me here?", "Можешь принести мне сюда попить?"),
    ("broke", "He broke the window with a ball.", "He made the glass fall apart by hitting it.", "Он заставил стекло развалиться, ударив по нему."),
    ("broken", "The broken chair is in the garden.", "The chair is in pieces and does not work.", "Стул развалился и им нельзя пользоваться."),
    ("brought", "She brought her friend to the party.", "She arrived with her friend at the party.", "Она пришла на вечеринку вместе с другом."),
    ("brush", "I brush my teeth every morning.", "I clean my teeth with a special tool.", "Я чищу зубы специальным инструментом каждое утро."),
    ("burn", "The old wood starts to burn.", "There is a fire on the wood.", "Дерево охвачено огнем."),
    ("burst", "The balloon will burst if you touch it.", "The air will go out fast with a loud sound.", "Воздух быстро выйдет с громким звуком."),
    ("business", "He wants to start a new business.", "He wants to open a shop to make money.", "Он хочет открыть магазин, чтобы зарабатывать деньги."),
    ("buy", "I want to buy a new book.", "I will give money to get a book.", "Я дам денег, чтобы получить книгу."),
    ("by", "The store is by the bus station.", "The store is next to the bus station.", "Магазин находится рядом с автобусной остановкой."),
    ("came", "He came to my house late.", "He arrived at my house late.", "Он прибыл ко мне домой поздно."),
    ("card", "She has a small white card in her bag.", "She has a small white object with her name in her bag.", "У неё в сумке лежит маленький белый предмет с её именем."),
    ("care", "The dog needs love and care.", "The dog needs someone to look after it.", "Собаке нужно, чтобы кто-то за ней присматривал."),
    ("carefully", "Please walk carefully on the ice.", "You should move slowly and watch your feet.", "Тебе стоит двигаться медленно и смотреть под ноги."),
    ("case", "This is a bad case for the police.", "It is a thing for the police to work on.", "Это работа для полиции."),
    ("catch", "Can you catch the ball for me?", "Can you hold the ball with your hands?", "Можешь ли ты удержать мяч в руках?"),
    ("caught", "The cat caught a small mouse yesterday.", "The cat got a small mouse in its paws.", "Кот схватил маленькую мышь своими лапами."),
    ("cell", "The bird is in a small metal cell.", "The bird is inside a cage with bars.", "Птица находится внутри клетки с прутьями."),
    ("chance", "You have a good chance to win.", "You can win now.", "У тебя есть возможность победить."),
    ("chase", "The big dog likes to chase the cat.", "The dog runs fast to follow the cat.", "Собака быстро бежит, чтобы следовать за котом."),
    ("cheek", "She has a red mark on her cheek.", "There is a mark on the side of her face.", "На боковой части лица у неё есть пятно."),
    ("children", "All the children are playing in the park.", "The young boys and girls are playing outside.", "Маленькие мальчики и девочки играют на улице."),
    ("chuckle", "He started to chuckle at the funny joke.", "He made a quiet laughing sound.", "Он издал тихий смеющийся звук."),
    ("class", "I go to my English class every Monday.", "I go to my lesson of English every Monday.", "Я хожу на урок английского каждый понедельник."),
    ("clean", "Please clean your room before you go out.", "Please make your room tidy and not dirty.", "Пожалуйста, сделай свою комнату опрятной и не грязной."),
    ("clothes", "I need to buy some new clothes today.", "I need to buy new shirts and pants.", "Мне нужно купить новые рубашки и брюки."),
    ("college", "My brother studies at a big college.", "He studies at a school after high school.", "Он учится в учебном заведении после школы."),
    ("color", "My red color is very bright.", "Red is a look that is not black or white.", "Красный — это не черный и не белый."),
    ("come", "Please come to my house today.", "Walk to my home now.", "Иди ко мне домой прямо сейчас."),
    ("come back", "When will you come back home from the shop?", "When will you return to your house?", "Когда ты вернешься домой?"),
    ("comment", "He wrote a nice comment under my photo.", "He wrote a short message about my photo.", "Он написал короткое сообщение о моей фотографии."),
    ("completely", "I am completely ready for the big trip.", "I am ready in every way for the trip.", "Я готов во всех отношениях к этой поездке."),
    ("concern", "The health of my dog is a big concern.", "I feel worried about the health of my dog.", "Я чувствую беспокойство о здоровье моей собаки."),
    ("confuse", "The two similar words confuse me a lot.", "I do not know which one is the right word.", "Я не знаю, какое из них верное слово."),
    ("conversation", "We had a long conversation about our new plans.", "They were talking to each other for a long time.", "Они долго разговаривали друг с другом."),
    ("couch", "I like to sit on the couch and watch TV.", "This is a soft piece of furniture for two or three people.", "Это мягкая мебель, на которой могут сидеть два или три человека."),
    ("counter", "The man at the counter gave me my coffee.", "The person behind the high table in a cafe gave me the drink.", "Человек за высокой стойкой в кафе дал мне кофе."),
    ("couple", "A young couple is walking in the park now.", "Two people are together in the park.", "Два человека гуляют вместе в парке."),
    ("course", "I want to start a new English course today.", "I want to begin a series of lessons to learn a language.", "Я хочу начать серию уроков, чтобы выучить язык."),
    ("cover", "Please cover the food with a clean plate.", "Put a plate on top of the food.", "Положи тарелку сверху на еду."),
    ("crack", "The old glass can crack if it is too hot.", "A small line can appear on the glass because of the heat.", "Из-за жары на стекле может появиться тонкая линия."),
    ("cross", "We walk to cross the big road now.", "Go from one part of the road to the other.", "Перейди с одной части дороги на другую."),
    ("crowd", "There is a big crowd at the concert tonight.", "Many people are in one place to see the show.", "Много людей собралось в одном месте, чтобы посмотреть шоу."),
    ("cup", "I drink my tea from this blue cup.", "You use this small thing to drink hot tea.", "Ты используешь эту маленькую вещь, чтобы пить горячий чай."),
    ("cute", "That little puppy is very cute.", "The small dog looks very nice and beautiful.", "Эта маленькая собачка выглядит очень приятно и красиво."),
    ("dad", "My dad works in a big office in the city.", "This is the man who is your father.", "Это мужчина, который является твоим отцом."),
    ("damn", "Damn, I forgot my keys at home again.", "You say this word when you are a little bit angry.", "Ты говоришь это слово, когда немного злишься."),
    ("dance", "They like to dance to good music at parties.", "People move their bodies to the rhythm of the song.", "Люди двигают телом в ритм песни."),
    ("dark", "It is dark outside because the sun is gone.", "There is no light in the room or on the street.", "В комнате или на улице нет света."),
    ("date", "I have a date with her on Friday night.", "You are meeting a person you like for a romantic evening.", "Ты встречаешься с человеком, который тебе нравится, для романтического вечера."),
    ("dear", "My dear friend, thank you for your help.", "This word shows that you love or like someone a lot.", "Это слово показывает, что ты очень любишь кого-то или относишься с симпатией."),
    ("death", "The death of the old man made us sad.", "This happens when someone stops living.", "Это случается, когда кто-то перестает жить."),
    ("definitely", "I will definitely come to your party tonight.", "I am sure that I will be at your party.", "Я уверен, что буду на вашей вечеринке."),
    ("desk", "My books are on my desk.", "There is a table where I study and work.", "Там есть стол, за которым я учусь и работаю."),
    ("did", "He did his homework after school.", "He finished his tasks after school.", "Он закончил свои задания после школы."),
    ("die", "Flowers die without water.", "Plants stop living if they have no water.", "Растения перестают жить, если у них нет воды."),
    ("direction", "Which direction is the train station?", "Where should I go to find the station?", "Куда мне идти, чтобы найти станцию?"),
    ("does", "She does her job very well.", "She performs her work very well.", "Она очень хорошо выполняет свою работу."),
    ("down", "Please put your bag down on the floor.", "Place your bag on the floor.", "Положи свою сумку на пол."),
    ("drag", "Can you drag this heavy box here?", "Can you pull this heavy box to this place?", "Ты можешь притянуть эту тяжелую коробку сюда?"),
    ("draw", "I like to draw a cat with a pen.", "You use a pen to make a picture.", "Ты используешь ручку, чтобы сделать картинку."),
    ("dream", "I have a big dream about a new house.", "It is a happy thought you have in your head.", "Это приятная мысль, которая у тебя в голове."),
    ("drink", "I drink water when I am thirsty.", "I swallow water when I need it.", "Я глотаю воду, когда мне это нужно."),
    ("drive", "I drive my car to work every day.", "I operate my car to get to work.", "Я управляю своей машиной, чтобы добраться до работы."),
    ("drove", "He drove the car to the city.", "He was the person operating the car to the city.", "Он был тем, кто вел машину до города."),
    ("during", "We stayed at home during the rain.", "We stayed at home for the time it was raining.", "Мы оставались дома в то время, пока шел дождь."),
    ("each", "I give an apple to each student.", "You give one to all people in the room.", "Ты даешь по одному всем людям в комнате."),
    ("easily", "She speaks English very easily.", "It is not hard for her to speak English.", "Ей несложно говорить по-английски."),
    ("eat", "I eat a red apple for my lunch.", "You put food in your mouth.", "Ты кладешь еду в рот."),
    ("either", "You can have tea or coffee, either is fine.", "You can pick one of these two options.", "Ты можешь выбрать один из двух вариантов."),
    ("else", "Do you want anything else to drink?", "Would you like some more to drink?", "Хотите что-нибудь еще попить?"),
    ("empty", "The bottle is empty now.", "There is nothing inside the bottle.", "В бутылке ничего нет."),
    ("end", "We watch the end of the movie.", "We watch the final part of the film.", "Мы смотрим последнюю часть фильма."),
    ("enough", "I have enough water for my long walk today.", "I do not need any more water now.", "Мне больше не нужно воды сейчас."),
    ("entire", "She read the entire book in one day.", "She read the whole book from start to finish.", "Она прочитала всю книгу целиком за один день."),
    ("especially", "I like fruit, especially apples.", "Apples are my favorite type of fruit.", "Яблоки — мой любимый вид фруктов."),
    ("even", "He is very fast, even in the rain.", "He runs quickly, also when the weather is bad.", "Он бегает быстро, даже когда погода плохая."),
    ("eventually", "Eventually we found the right house.", "After a long time we finally found the house.", "В конце концов, мы нашли нужный дом."),
    ("ever", "Have you ever been to London?", "At any time in your life, did you visit London?", "Ты когда-нибудь бывал в Лондоне?"),
    ("every", "I drink coffee every morning at my home.", "I do this on all mornings of the week.", "Я делаю это каждое утро на неделе."),
    ("everyone", "Everyone is here for the party.", "All the people are present at the party.", "Все здесь на вечеринке."),
    ("everything", "I want everything in this shop.", "I want all the things in this store.", "Я хочу всё в этом магазине."),
    ("exactly", "That is exactly what I need.", "That is precisely the thing I need.", "Это именно то, что мне нужно."),
    ("except", "Everyone is here except John.", "All people are present but John is not.", "Все здесь, кроме Джона."),
    ("excite", "The new toys excite the small children.", "The new toys make the children feel very happy and active.", "Новые игрушки приводят детей в восторг."),
    ("exclaim", "Wow, look at that! she did exclaim.", "She said those words with strong feelings.", "Ого, посмотри на это! воскликнула она."),
    ("excuse", "She has a good excuse for being late today.", "She has a story to explain why she is not on time.", "У нее есть история, чтобы объяснить, почему она не пришла вовремя."),
    ("expression", "She had a happy expression on her face.", "Her face showed that she was feeling happy.", "У нее было радостное выражение лица."),
    ("eyebrow", "She moved her eyebrow in surprise.", "The hair above her eye moved because she was surprised.", "Она удивленно повела бровью."),
    ("fall", "Do not fall on the wet floor in the kitchen.", "You can go down to the floor by mistake.", "Ты можешь случайно оказаться на полу."),
    ("far", "My house is very far from the school.", "It is a long way to walk from my home.", "До моего дома идти очень долго."),
    ("favorite", "Red is my favorite color.", "I like this color more than all other colors.", "Этот цвет мне нравится больше всех остальных."),
    ("fear", "He has a big fear of spiders.", "He feels very scared when he sees a spider.", "Ему очень страшно, когда он видит паука."),
    ("feet", "My feet are tired after a long walk.", "These parts of your body are at the end of your legs.", "Эти части твоего тела находятся в самом низу ног."),
    ("fell", "The boy fell on the wet grass.", "He went down to the ground by mistake.", "Он по ошибке оказался на земле."),
    ("felt", "I felt sad when the movie ended.", "I was unhappy when the film was over.", "Мне стало грустно, когда фильм закончился."),
    ("few", "I have a few apples in my bag.", "I have some apples, but not many.", "У меня есть немного яблок, но не много."),
    ("fight", "Bad boys sometimes fight at school.", "They hit each other with their hands.", "Они бьют друг друга руками."),
    ("figure out", "I need to figure out how this new phone works.", "I need to find the answer to how this device works.", "Мне нужно найти ответ на то, как работает это устройство."),
    ("fill", "Please fill the glass with cold water.", "Put water in the glass until it is full.", "Налей воду в стакан до краев."),
    ("finally", "I finally finished my difficult homework.", "After a long time, the work is done.", "Спустя долгое время работа наконец сделана."),
    ("find", "Can you find my blue pen?", "Look for my pen and get it for me.", "Поищи мою ручку и принеси её мне."),
    ("find out", "I want to find out the time of the movie.", "I need to learn or discover the start time.", "Мне нужно узнать время начала фильма."),
    ("fine", "I am fine, thank you for asking.", "I am doing well today.", "У меня всё хорошо, спасибо."),
    ("fire", "We sit by the fire to stay warm.", "We sit near the hot flames to get heat.", "Мы сидим рядом с горячим пламенем, чтобы согреться."),
    ("first", "This is my first day at work.", "This is the day number one for me.", "Это мой самый начальный день на работе."),
    ("fit", "This shirt does not fit me well.", "The size is not right for my body.", "Этот размер мне не подходит."),
    ("five", "I have five red pencils on my desk.", "I have one plus four pencils.", "У меня есть один плюс четыре карандаша."),
    ("flash", "I saw a bright flash in the sky.", "A sudden quick light appeared in the air.", "В воздухе внезапно появился быстрый свет."),
    ("flip", "Please flip the pancake to the other side.", "Turn the pancake over.", "Переверни блин на другую сторону."),
    ("for", "This gift is for my mother.", "I bought this present to give to her.", "Я купил этот подарок, чтобы отдать ей."),
    ("force", "The police force the door open to enter the house.", "They use a lot of power to push it open.", "Они применяют много силы, чтобы толкнуть дверь и открыть её."),
    ("form", "The snow starts to form a white layer on the ground.", "It begins to make a shape on the floor.", "Оно начинает принимать очертания на земле."),
    ("forward", "Please move your chair forward to see the screen.", "Move it to the place in front of you.", "Передвинь его на место перед собой."),
    ("found", "I found my red pen on the floor.", "My lost item is now in my hand.", "Моя потерянная вещь теперь у меня в руке."),
    ("four", "There are four red apples on the table.", "You can count them: one, two, three and one more.", "Ты можешь посчитать их: один, два, три и ещё один."),
    ("from", "This letter is from my best friend in London.", "The person who sent it is in another city.", "Тот, кто отправил это, находится в другом городе."),
    ("front", "My house is at the front of the street.", "It is at the very beginning of the road.", "Он стоит в самом начале улицы."),
    ("frown", "Do not frown when you are sad about the test.", "Do not move your face to show you are unhappy.", "Не двигай лицом, чтобы показать, что ты расстроен."),
    ("fuck", "Oh fuck, I forgot my keys at home again.", "A bad word people say when they are very angry.", "Плохое слово, которое люди говорят, когда они очень злы."),
    ("fun", "It is great fun to play in the park.", "It makes you feel very happy and good.", "Это заставляет тебя чувствовать себя очень счастливым."),
    ("further", "We can walk further to find a nice shop.", "We can go a longer distance to see more.", "Мы можем пройти более длинную дистанцию, чтобы увидеть больше."),
    ("game", "This is a fun game for the kids.", "Children like to play this activity.", "Детям нравится играть в это занятие."),
    ("gasp", "I gasp when I see the big surprise gift.", "You take a quick breath because you are shocked.", "Ты быстро вдыхаешь, потому что ты в шоке."),
    ("gave", "He gave a nice book to his mom.", "He put the book in her hand as a present.", "Он вложил книгу ей в руку в качестве подарка."),
    ("gaze", "She likes to gaze at the stars at night.", "She looks at them for a long time without moving.", "Она смотрит на них долгое время, не двигаясь."),
    ("gently", "Please hold the baby gently in your arms.", "Hold the child with a lot of care and love.", "Держи ребёнка с большой заботой и любовью."),
    ("get", "I get a new letter from my friend today.", "The letter is here for me now.", "Письмо теперь у меня."),
    ("get up", "I usually get up at seven in the morning.", "I leave my bed at seven every day.", "Я обычно встаю с кровати в семь утра."),
    ("giggle", "The children giggle when they hear a funny story.", "They make a quiet sound of laughing.", "Они издают тихий смеющийся звук."),
    ("girl", "The young girl is playing with her red ball.", "A child who is not a boy.", "Ребёнок, который не является мальчиком."),
    ("girlfriend", "My girlfriend is coming to the party with me.", "The woman who you love and date.", "Женщина, которую ты любишь и с которой встречаешься."),
    ("give", "Please give me the red pen.", "Can you hand the red pen to me?", "Можешь передать мне красную ручку?"),
    ("give up", "Do not give up even if the test is hard.", "Do not stop trying when things are difficult.", "Не прекращай попыток, даже когда всё сложно."),
    ("given", "The given answer is not correct.", "The answer provided is not right.", "Предоставленный ответ неверный."),
    ("glad", "I am so glad to see you.", "I feel very happy to see you.", "Я очень счастлив тебя видеть."),
    ("glance", "She took a quick glance at the clock.", "She looked at the clock for a very short time.", "Она быстро посмотрела на часы."),
    ("glare", "He began to glare at his angry boss.", "He looked at his boss in a very mean way.", "Он начал сердито смотреть на своего злого начальника."),
    ("glass", "I drink water from a glass.", "I use this cup for my water.", "Я пью воду из этого стакана."),
    ("go", "I go to school every day.", "I walk to school every day.", "Я хожу в школу каждый день."),
    ("go on", "Please go on with your story now.", "Do not stop, tell me more.", "Не останавливайся, рассказывай дальше."),
    ("god", "People pray to God in church.", "People pray to the creator in church.", "Люди молятся Богу в церкви."),
    ("gone", "My friend is gone to the park.", "He is not here right now, he is at the park.", "Его сейчас здесь нет, он в парке."),
    ("gonna", "I am gonna eat an apple now.", "I am going to eat an apple now.", "Я собираюсь съесть яблоко сейчас."),
    ("got", "I got a nice gift today.", "I received a nice gift today.", "Я получил хороший подарок сегодня."),
    ("gotten", "The letter was gotten by my brother.", "The letter was received by my brother.", "Письмо было получено моим братом."),
    ("grab", "Grab my hand before you fall.", "Hold my hand quickly before you fall.", "Схвати меня за руку, прежде чем упадешь."),
    ("great", "That is a great idea for us.", "That is a very good idea for us.", "Это отличная идея для нас."),
    ("grin", "He had a big grin on his face.", "He had a very big smile on his face.", "У него была широкая улыбка на лице."),
    ("grip", "You need a strong grip on the rope.", "You need to hold the rope very hard.", "Тебе нужно крепко держаться за веревку."),
    ("groan", "I heard a deep groan from his room.", "I heard a sad sound from his room.", "Я услышал тяжелый стон из его комнаты."),
    ("grow up", "I want to be a pilot when I grow up.", "I want to fly planes when I become an adult.", "Я хочу быть пилотом, когда стану взрослым."),
    ("guard", "The guard stands at the front door.", "The man who watches the door is here.", "Охранник стоит у входной двери."),
    ("gun", "The police officer has a gun.", "The police officer has a weapon.", "У полицейского есть оружие."),
    ("guy", "Who is that guy in the room?", "Who is that man in the room?", "Кто этот парень в комнате?"),
    ("had", "I had a blue pen yesterday.", "The pen was in my hand before now.", "Эта ручка была у меня до этого момента."),
    ("half", "I want half of the big cake.", "You cut the food into two parts and take one.", "Ты разрезаешь еду на две части и берешь одну."),
    ("hall", "The music in the hall is very loud.", "The music in the big room is very loud.", "Музыка в большом помещении очень громкая."),
    ("hallway", "Leave your coat in the hallway.", "Leave your coat in the area near the front door.", "Оставь пальто в зоне у входной двери."),
    ("handle", "Open the door with this metal handle.", "Open the door with this part you hold with your hand.", "Открой дверь за эту штуку, которую держат рукой."),
    ("has", "She has a small cat at home.", "She keeps a small cat at her home.", "У нее дома живет маленький кот."),
    ("have", "I have a new red car.", "The car is with me now.", "Эта машина сейчас у меня."),
    ("having", "Having a dog makes me very happy.", "Owning a dog makes me very happy.", "Владение собакой делает меня очень счастливым."),
    ("he", "He is my best friend at school.", "That boy is my best friend at school.", "Этот парень — мой лучший друг в школе."),
    ("hear", "Can you hear the birds outside?", "Can you listen to the birds outside?", "Ты можешь уловить звуки птиц снаружи?"),
    ("heard", "I heard a nice song on the radio today.", "My ears got the music from the radio.", "Мои уши уловили музыку с радио."),
    ("hell", "It felt like hell during the hot day.", "It felt like a very bad place during the hot day.", "В этот жаркий день было невыносимо плохо."),
    ("hello", "Say hello to your mother for me.", "Say hi to your mother for me.", "Передай привет своей маме от меня."),
    ("her", "This is her new yellow bag.", "The bag belongs to that girl.", "Эта сумка принадлежит той девушке."),
    ("herself", "She made a cake for herself at home.", "She cooked the food for no one but her.", "Она приготовила еду только для себя."),
    ("hey", "Hey, look at that big yellow bus!", "Listen, look at that big yellow bus!", "Слушай, посмотри на тот большой желтый автобус!"),
    ("hi", "Hi, how are you today?", "Hello, how are you today?", "Привет, как у тебя дела сегодня?"),
    ("hide", "The children like to hide under the bed.", "The children like to go where people cannot see them.", "Дети любят забираться туда, где их не видно."),
    ("him", "I see him in the park often.", "I see that boy in the park often.", "Я часто вижу того парня в парке."),
    ("himself", "He saw himself in the big mirror.", "He looked at the person in the mirror and it was he.", "Он посмотрел на человека в зеркале, и это был он."),
    ("his", "This is his red car.", "The vehicle belongs to that man.", "Эта машина принадлежит тому мужчине."),
    ("hold", "Please hold my hand now.", "Keep my hand in your hand.", "Не отпускай мою руку."),
    ("holding", "The baby is holding my hand now.", "You keep a small thing in your hand.", "Вы держите маленькую вещь в руке."),
    ("horrible", "The weather is horrible today.", "The weather is very bad and unpleasant.", "Погода сегодня очень плохая и неприятная."),
    ("however", "I like him, however he is late.", "I like him but he is not on time.", "Он мне нравится, но он опаздывает."),
    ("hug", "I want to hug my mom.", "I want to put my arms around my mom.", "Я хочу заключить маму в объятия."),
    ("huge", "The dog is huge and strong.", "The dog is very big.", "Эта собака очень большая."),
    ("human", "Every human needs to eat food.", "Every person needs to eat food.", "Каждому человеку нужно есть еду."),
    ("hundred", "I have one hundred apples here.", "I have ten times ten apples here.", "У меня здесь десять раз по десять яблок."),
    ("hung", "The picture hung on the wall.", "The picture was on the wall above the floor.", "Картина находилась на стене над полом."),
    ("i feel dizzy", "I feel dizzy and need to sit down now.", "The room is turning around and I want to fall.", "Комната вращается, и мне кажется, что я упаду."),
    ("i have a booking", "I have a booking for two nights at this hotel.", "I already reserved a room for my stay here.", "Я уже зарезервировал номер для проживания здесь."),
    ("i have a fever", "I have a fever and need some water.", "My body is hot and not good.", "Мое тело горячее и мне нехорошо."),
    ("i have a headache", "I have a headache, can I have some water?", "The top part of my body has a lot of pain.", "Верхняя часть моего тела очень сильно болит."),
    ("i have a reservation", "I have a reservation for two people.", "I already booked a table for us.", "Я уже забронировал столик для нас."),
    ("i have a sore throat", "I have a sore throat and cannot speak well.", "My neck hurts when I try to swallow food.", "У меня болит шея внутри, когда я пытаюсь глотать еду."),
    ("i need a doctor", "I need a doctor because I am very sick.", "I need to see the person who helps sick people.", "Мне нужно встретиться с человеком, который помогает больным."),
    ("i'm sorry", "I'm sorry for being late today.", "Say this when you feel bad about a mistake.", "Скажи это, если чувствуешь вину за ошибку."),
    ("ice", "Put some ice in the drink.", "Put some frozen water in the drink.", "Положи немного замороженной воды в напиток."),
    ("idea", "That is a good idea for us.", "That is a good thought for us.", "Это хорошая мысль для нас."),
    ("if", "Call me if you are sad.", "When you are sad, call me.", "Когда тебе будет грустно, позвони мне."),
    ("ignore", "Please do not ignore my message.", "Do not look at it and do not answer.", "Не смотри на это и не отвечай."),
    ("ill", "He is ill in his bed.", "He is not healthy and stays in bed.", "Он не здоров и лежит в кровати."),
    ("immediately", "Come here immediately to help me.", "Come here right now to help me.", "Приходи сюда прямо сейчас, чтобы помочь мне."),
    ("impossible", "It is impossible to finish this task today.", "You can not do this, it is not real.", "Ты не можешь это сделать, это нереально."),
    ("in", "The cat is in the box.", "The cat is inside the box.", "Кот находится внутри коробки."),
    ("inch", "This small screen is ten inches wide.", "It is a unit of length used in the USA.", "Это единица длины, которую используют в США."),
    ("include", "The price includes a hot cup of tea.", "The cost has this drink in it too.", "В стоимость уже входит этот напиток."),
    ("indeed", "It is indeed a very cold winter day.", "You are truly right about the weather.", "Ты действительно прав насчет погоды."),
    ("inside", "The cat is inside the box.", "The cat is in the small house for pets.", "Кот находится в маленьком домике для питомцев."),
    ("instead", "I want tea instead of hot coffee.", "I prefer this drink and not that one.", "Я хочу этот напиток, а не тот."),
    ("interest", "She has a great interest in music.", "She really likes to listen to songs.", "Ей очень нравится слушать песни."),
    ("into", "He walked into the big green house.", "He moved from the outside to the room.", "Он переместился с улицы в комнату."),
    ("invade", "The army will invade the small town.", "Soldiers enter a place to take control.", "Солдаты входят в город, чтобы захватить его."),
    ("invisible", "The ghost is invisible to my eyes.", "You cannot see this thing at all.", "Ты совсем не можешь это увидеть."),
    ("is", "My mother is a very kind woman.", "She acts as a nice person every day.", "Она выступает в роли доброго человека."),
    ("it", "Look at the dog, it is hungry.", "Use this word to talk about the animal.", "Используй это слово, чтобы сказать о животном."),
    ("it depends", "Can we go now? It depends on the weather.", "The answer is not clear, it changes based on other things.", "Ответ не ясен, он меняется в зависимости от других вещей."),
    ("it's", "It's time to go home right now.", "This moment is the hour to leave.", "Этот момент — время уходить домой."),
    ("its", "The cat lost its red toy today.", "The toy belongs to that animal.", "Эта игрушка принадлежит тому животному."),
    ("itself", "The cat cleans itself every day.", "The cat makes the cat clean.", "Кот делает так, чтобы он был чистым."),
    ("jail", "The bad man is in the jail.", "This is a place for people who break laws.", "Это место для людей, которые нарушают закон."),
    ("job", "I have a new job at school.", "This is the work that brings me money.", "Это занятие, которое приносит мне деньги."),
    ("joke", "He told a funny joke to us.", "He said something that makes people laugh.", "Он сказал то, от чего люди смеются."),
    ("just", "I just arrived at the train station.", "I came here a very short time ago.", "Я пришел сюда совсем недавно."),
    ("keep", "Please keep your room very clean today.", "Try to hold the area in good condition.", "Постарайся содержать это место в порядке."),
    ("kept", "She kept the secret for many years.", "She did not tell the story to anyone.", "Она не рассказала эту историю никому."),
    ("key", "I have the key to my house in my bag.", "You use this small metal object to open a locked door.", "Этот маленький металлический предмет нужен, чтобы открыть запертую дверь."),
    ("kid", "That little kid plays in the park every day.", "A very young person who is not an adult.", "Очень молодой человек, который еще не взрослый."),
    ("kill", "The bad man wants to kill the cat.", "He wants the small animal to be dead now.", "Он хочет, чтобы маленькое животное сейчас умерло."),
    ("killed", "The poor bird was killed by the cat.", "The animal is now dead because of another animal.", "Животное больше не живо из-за другого животного."),
    ("kind", "She is a very kind woman to everyone.", "A person who is nice and likes to help others.", "Человек, который ведет себя мило и любит помогать другим."),
    ("kiss", "She gives her mom a kiss on her face.", "You show love when your lips meet someone.", "Ты показываешь любовь, когда твои губы касаются кого-то."),
    ("knew", "I knew the answer to the simple test.", "You have the info in your head.", "У тебя есть эта информация в голове."),
    ("knife", "Use a sharp knife to cut the red apple.", "A tool made of metal used for cutting food.", "Металлический инструмент, который используют, чтобы резать еду."),
    ("know", "I know your name and your address.", "You have this information in your head.", "У тебя есть эта информация в голове."),
    ("known", "He is a known man in this small town.", "Many people have heard of this person.", "Многие люди слышали об этом человеке."),
    ("lady", "The lady is walking in the park.", "This is a word for a woman.", "Это слово для обозначения женщины."),
    ("laid", "He laid the book on the table.", "He put it down on the top of the table.", "Он положил это на верх стола."),
    ("land", "The plane will land at the airport now.", "The plane goes down to the earth.", "Самолет опускается на землю."),
    ("language", "I want to learn a new language.", "People use this to talk and write.", "Люди используют это, чтобы говорить и писать."),
    ("large", "They have a large house with many rooms.", "It is not small.", "Это не маленькое."),
    ("last", "This movie will last for two hours.", "It does not stop for a long time.", "Это не останавливается долгое время."),
    ("later", "I will call you later this evening.", "At a time after now.", "В какое-то время после сейчас."),
    ("lay", "Please lay your bags on the floor here.", "Put your things down on a flat place.", "Положи свои вещи на плоское место."),
    ("leader", "She is a great leader of our team.", "She is the person in charge of our group.", "Она человек, который руководит нашей группой."),
    ("least", "This is the least expensive shirt in the shop.", "It costs less money than all other shirts here.", "Она стоит меньше денег, чем все остальные рубашки здесь."),
    ("left", "He left his house at eight in the morning.", "He went away from his home early today.", "Он ушел из дома рано сегодня утром."),
    ("less", "I want less sugar in my tea, please.", "Please put a smaller amount of sugar in my cup.", "Пожалуйста, положи меньшее количество сахара в мою чашку."),
    ("let", "Please let me play with your new toy.", "Can you give me permission to use your toy?", "Можешь дать мне разрешение поиграть с твоей игрушкой?"),
    ("let me call you back", "I am busy now, let me call you back later.", "I will phone you again in a short time.", "Я позвоню тебе снова через некоторое время."),
    ("letter", "I write a short letter to my friend.", "You send this paper with words to a person.", "Ты отправляешь этот листок со словами другому человеку."),
    ("lie", "Do not lie to me about where you are.", "Do not say things that are not right.", "Не говори того, что не является правдой."),
    ("life", "I love my life and my family.", "It is the time from your birth to your end.", "Это время от твоего рождения до самого конца."),
    ("lift", "Can you help me lift this heavy box?", "Can you move this box up with your hands?", "Ты можешь поднять эту коробку руками?"),
    ("light", "Please turn on the light in the room.", "Make the room bright so I can see.", "Сделай комнату светлой, чтобы я мог видеть."),
    ("lip", "She has a small cut on her lip.", "There is a small mark on the part of her mouth.", "Есть небольшая ранка на части её рта."),
    ("little", "I have a little cat in my house.", "It is not big.", "Он совсем не большой."),
    ("look after", "Can you look after my cat for one day?", "Can you take care of my pet while I am away?", "Можешь присмотреть за моим питомцем, пока меня нет?"),
    ("look for", "I need to look for my keys in the bag.", "I am trying to see where my keys are.", "Я пытаюсь понять, где мои ключи."),
    ("look forward to", "I look forward to our meeting next week.", "I am very happy to wait for our next meeting.", "Я с большим удовольствием жду нашей следующей встречи."),
    ("lost", "I lost my keys in the park today.", "I cannot find my keys anywhere now.", "Я нигде не могу найти свои ключи сейчас."),
    ("lucky", "You are very lucky to win this game.", "Good things happen to you in this game.", "Хорошие вещи случаются с тобой в этой игре."),
    ("machine", "The washing machine is in the kitchen.", "It is a thing that works to help you.", "Это вещь, которая работает, чтобы тебе помогать."),
    ("mad", "My brother was mad when I broke his toy.", "He was very angry with me.", "Он был очень зол на меня."),
    ("magic", "The book is about magic and dragons.", "The story has strange and special powers in it.", "В этой истории есть странные и особые силы."),
    ("main", "This is the main road to the city.", "This is the most important street for cars.", "Это самая важная улица для машин."),
    ("many", "There are many people at the park.", "A large number of people are here.", "Здесь находится большое количество людей."),
    ("maybe", "Maybe I will go to the park later today.", "I am not sure, but I can go to the park.", "Я не уверен, но, возможно, схожу в парк."),
    ("mean", "What does this new word mean for you?", "Tell me what this word is about.", "Скажи, что это слово означает для тебя."),
    ("meant", "I meant to call you yesterday evening.", "I had the plan to call you yesterday.", "Я собирался позвонить тебе вчера вечером."),
    ("meet", "Let us meet at the station at five.", "Let us see each other at the station.", "Давай встретимся на станции в пять."),
    ("memory", "She has a very good memory for names.", "She can keep many names in her head.", "У нее очень хорошая память на имена."),
    ("message", "I got a short message from my friend.", "I received a small text from my friend.", "Я получил короткое сообщение от друга."),
    ("might", "It might rain later in the day.", "There is a chance of rain today.", "Возможно, сегодня позже пойдет дождь."),
    ("mile", "The house is one mile from the sea.", "The house is a short distance from the sea.", "Дом находится в одной миле от моря."),
    ("mind", "Do you mind if I sit here?", "Are you against me sitting here?", "Ты не против, если я здесь сяду?"),
    ("mine", "That red car is mine.", "That red car belongs to me.", "Эта красная машина — моя."),
    ("miss", "I miss my family when I am away.", "I feel sad because I am not with my family.", "Я скучаю по своей семье, когда я в отъезде."),
    ("mistake", "It was a big mistake to go there.", "I did something wrong by going there.", "Это была большая ошибка — идти туда."),
    ("moment", "Wait a moment, I will be ready soon.", "Wait a very short time, please.", "Подожди минутку, я скоро буду готов."),
    ("moon", "The moon is very bright tonight.", "The white circle in the night sky is bright.", "Луна сегодня ночью очень яркая."),
    ("more", "I need more water for my plants.", "I need an extra amount of water.", "Мне нужно больше воды для моих растений."),
    ("most", "Most people like to sleep at night.", "The big part of people like to sleep at night.", "Большинство людей любят спать по ночам."),
    ("movie", "We watched a funny movie last night.", "We saw a long video story at the cinema.", "Мы смотрели смешной фильм вчера вечером."),
    ("much", "Thank you so much for your big help.", "I am very happy and say thanks a lot.", "Я очень рад и говорю большое спасибо."),
    ("murder", "The police look for the person after the murder.", "The police look for the person who killed someone.", "Полиция ищет человека после убийства."),
    ("music", "I like to listen to good music at home.", "I like to hear nice songs and sounds.", "Мне нравится слушать приятные песни и звуки."),
    ("must", "I must go to school now.", "It is necessary for me to go to school now.", "Мне необходимо сейчас идти в школу."),
    ("my", "This is my red pen.", "The red pen belongs to me.", "Эта красная ручка принадлежит мне."),
    ("my battery is dying", "My battery is dying fast because I use the phone all day.", "The power in my mobile is very low and it will turn off soon.", "Заряд моего телефона почти на нуле, скоро он выключится."),
    ("myself", "I talk to myself when I am happy.", "I speak to me and nobody is there.", "Я говорю с самим собой, когда никого нет рядом."),
    ("nation", "The nation is very big and old.", "All the people in this country are one group.", "Все люди в этой стране составляют одну группу."),
    ("natural", "It is a natural place with many trees.", "It is not made by people, it is from the earth.", "Это создано не людьми, а самой природой."),
    ("nearly", "It is nearly time to go home.", "It is almost time to leave.", "Почти настало время уходить."),
    ("needed", "I needed a pen for my test.", "I had to have a pen for my test.", "Мне требовалась ручка для контрольной."),
    ("neighbor", "My neighbor lives in the house next door.", "The person who lives near my house is nice.", "Человек, который живет рядом с моим домом, милый."),
    ("neither", "Neither cat is big.", "The first cat is not big and the second cat is not big.", "Ни первая кошка не большая, ни вторая."),
    ("never", "I never drink cold milk.", "I do not drink cold milk at any time.", "Я не пью холодное молоко ни при каких обстоятельствах."),
    ("never mind", "I broke the cup. Never mind, it is old.", "Do not worry about it, it is not important.", "Не переживай об этом, это не важно."),
    ("news", "I watch the news on TV every day.", "I listen to new stories about the world on TV.", "Я слушаю новые истории о мире по телевизору."),
    ("nice to meet you", "It is nice to meet you, my friend.", "I am happy that I know you now.", "Я рад, что теперь мы знакомы."),
    ("nine", "I have nine red apples.", "I have one more than eight apples.", "У меня на одно яблоко больше, чем восемь."),
    ("no", "No, I do not want any cake.", "I say that I do not want the cake.", "Я говорю, что не хочу торт."),
    ("no ice, please", "I would like a cold drink with no ice, please.", "Please do not put frozen water in my drink.", "Пожалуйста, не кладите замороженную воду в мой напиток."),
    ("no problem", "You can use my pen, no problem.", "It is fine, do not worry about it.", "Все в порядке, не переживай об этом."),
    ("nobody", "Nobody is in the room right now.", "There are zero people in the room.", "В комнате сейчас ноль людей."),
    ("nod", "I nod my head to say yes.", "I move my head up and down to say yes.", "Я двигаю головой вверх-вниз, чтобы сказать да."),
    ("none", "None of the students are here today.", "Zero students are here today.", "Ни одного студента сегодня здесь нет."),
    ("noon", "We eat lunch at noon.", "We eat at twelve o'clock in the day.", "Мы едим в двенадцать часов дня."),
    ("nor", "I like neither tea nor coffee.", "I do not like tea and I do not like coffee.", "Я не люблю чай и я не люблю кофе."),
    ("north", "The cold wind comes from the north.", "It is the way to the top of the map.", "Это направление в верхней части карты."),
    ("nothing", "I have nothing in my bag today.", "There is zero items inside my bag.", "В моей сумке совсем нет вещей."),
    ("obviously", "She is obviously happy with her new job.", "It is clear to everyone that she likes her work.", "Всем ясно, что ей нравится её работа."),
    ("ocean", "We like to swim in the blue ocean.", "It is a very big area of salt water.", "Это очень большая территория с солёной водой."),
    ("of", "I want a cup of hot tea.", "This word shows what the object is made from.", "Это слово показывает, из чего состоит предмет."),
    ("of course", "Can you help me? Of course I can.", "Yes, I will certainly do that for you.", "Да, я непременно сделаю это для тебя."),
    ("off", "Please turn off the lamp at night.", "Stop the light from working.", "Сделай так, чтобы свет перестал работать."),
    ("often", "I often walk to school in the morning.", "I walk to school many times every week.", "Я хожу в школу много раз каждую неделю."),
    ("oh", "Oh, I forgot my keys at home!", "A word you say when you are surprised.", "Слово, которое говорят, когда удивлены."),
    ("oil", "Put some oil in the pan to cook.", "A liquid used for frying food.", "Жидкость, которую используют для жарки еды."),
    ("okay", "It is okay to be late sometimes.", "It is fine and not a big problem.", "Это нормально и не является большой проблемой."),
    ("on", "The cat is on the table now.", "The cat is touching the top of the table.", "Кот касается поверхности стола."),
    ("once", "I saw him once at the cinema.", "I saw him only one time.", "Я видел его всего один раз."),
    ("one", "I have one apple for my lunch.", "The number before two.", "Число, которое идет перед двойкой."),
    ("one ticket, please", "One ticket, please, for the bus to the city.", "I want to buy a small paper for my trip.", "Я хочу купить бумажку для своей поездки."),
    ("only", "I have only five dollars in my pocket.", "I do not have more than that amount.", "У меня нет суммы больше, чем эта."),
    ("opening", "The opening of the new shop is today.", "The first day when a business starts working.", "Первый день, когда бизнес начинает работу."),
    ("opposite", "My house is opposite the big park.", "My house is on the other side of the road.", "Мой дом находится по другую сторону дороги."),
    ("or", "Do you want tea or coffee now?", "You can pick tea, and you can pick coffee.", "Ты можешь выбрать чай, а можешь выбрать кофе."),
    ("other", "I have one book and one other book.", "I have one book and one more book that is not this one.", "У меня есть одна книга и ещё одна книга, не эта."),
    ("our", "This is our house in the city.", "The house belongs to us.", "Этот дом принадлежит нам."),
    ("ourselves", "We made the cake by ourselves.", "Nobody helped us make the cake.", "Никто не помогал нам печь этот торт."),
    ("out", "Let us go out for a walk.", "Leave the building and go to the street.", "Выйти из здания на улицу."),
    ("outside", "It is cold outside so wear a warm coat today.", "Not in the house.", "Не внутри дома."),
    ("over", "The lamp is over the desk.", "The light is high and not touching the table.", "Свет находится высоко и не касается стола."),
    ("pair", "I need a new pair of black shoes.", "Two things that go together.", "Две вещи, которые подходят друг другу."),
    ("partner", "My dance partner is very good at dancing.", "The person you work or play with.", "Человек, с которым ты работаешь или играешь."),
    ("party", "We have a fun party at home tonight.", "A meeting with friends, music and food.", "Встреча с друзьями, музыкой и едой."),
    ("pass", "We pass the school on our way home.", "To go by a place.", "Проходить мимо какого-то места."),
    ("past", "I do not think about the past anymore.", "The time that is gone.", "Время, которое ушло."),
    ("path", "Follow this small path to the lake.", "A road for people to walk on.", "Дорожка, по которой ходят люди."),
    ("pay", "I pay for the coffee at the shop.", "I give money for the coffee.", "Я отдаю деньги за кофе."),
    ("pen", "Can I have your blue pen, please?", "Can I use your thing to write with?", "Можно мне взять твою вещь, чтобы писать?"),
    ("perhaps", "Perhaps we can go to the park tomorrow.", "Maybe it will happen.", "Возможно, это случится."),
    ("period", "This long period of rain is very boring.", "A length of time.", "Промежуток времени."),
    ("person", "There is a nice person at the door.", "A man, woman or child.", "Мужчина, женщина или ребенок."),
    ("personal", "This is my personal letter, please do not read it.", "Belonging to just one human.", "Принадлежит только одному человеку."),
    ("photo", "Look at this nice photo of my family.", "A picture made with a camera.", "Картинка, сделанная камерой."),
    ("pick up", "Can you pick up my sister from the airport?", "Can you go and collect my sister in your car?", "Можешь заехать за моей сестрой в аэропорт?"),
    ("picture", "I like this picture on the wall.", "A drawing or a painting.", "Рисунок или картина."),
    ("plane", "The big plane flies in the sky.", "The big transport moves in the air.", "Этот большой транспорт летает в небе."),
    ("plastic", "This cup is made of hard plastic.", "A material that is not metal or wood.", "Материал, который не является металлом или деревом."),
    ("player", "The football player runs very fast on the field.", "This person does sports in a team game.", "Этот человек занимается спортом в командной игре."),
    ("please", "Can you open the door, please?", "Use this word to be nice when you ask for something.", "Используй это слово, чтобы быть вежливым, когда о чем-то просишь."),
    ("pleasure", "It is a pleasure to meet you today.", "You feel happy and good about this situation.", "Ты чувствуешь себя счастливым и довольным в этой ситуации."),
    ("point", "Do not point your finger at other people.", "Show where something is with your hand.", "Покажи рукой, где что-то находится."),
    ("police", "The police help people in the city.", "These people wear uniforms and keep the town not bad.", "Эти люди носят форму и следят за порядком в городе."),
    ("polite", "It is polite to say thank you to friends.", "You have good manners and act well.", "У тебя хорошие манеры, и ты ведешь себя достойно."),
    ("popular", "This song is very popular in my country.", "Many people know and like this thing.", "Многие люди знают и любят эту вещь."),
    ("position", "He has a good position in his company.", "This is your job title or where you stand.", "Это твоя должность на работе или место, где ты стоишь."),
    ("post", "I go to the post to send a letter.", "This place sends your mail to other cities.", "Это место отправляет твою почту в другие города."),
    ("pound", "This book costs only one pound.", "This is the money they use in the UK.", "Это деньги, которые используют в Великобритании."),
    ("present", "I have a nice present for your birthday.", "You give this to someone on their special day.", "Ты даришь это кому-то в их особенный день."),
    ("president", "The president talks to the people on TV.", "This person is the leader of a country.", "Этот человек является лидером страны."),
    ("pretty", "She has a pretty dress for the party.", "Something that looks very nice and beautiful.", "Что-то, что выглядит очень мило и красиво."),
    ("prince", "The prince lives in a big old castle.", "The son of a king.", "Сын короля."),
    ("princess", "The princess wears a gold crown today.", "The daughter of a king.", "Дочь короля."),
    ("print", "Can you print this document for me now?", "Make words from the computer appear on paper.", "Сделай так, чтобы слова с компьютера появились на бумаге."),
    ("prison", "The bad man stays in prison for years.", "A place where people go when they break the law.", "Место, куда люди попадают, когда нарушают закон."),
    ("probably", "I will probably go to the park later.", "It is likely to happen, but not sure.", "Это скорее всего случится, но не точно."),
    ("problem", "I have a big problem with my car.", "Something is wrong and I do not know what to do.", "Что-то не так, и я не знаю, что делать."),
    ("produce", "They produce good food at this big farm.", "To make or create something in large numbers.", "Создавать или делать что-то в больших количествах."),
    ("product", "This new product is very good for your skin.", "You can buy this item in the shop.", "Вы можете купить этот товар в магазине."),
    ("profession", "What is your father's profession?", "What kind of work does he do every day?", "Какую работу он выполняет каждый день?"),
    ("program", "I watch my favorite program on TV at eight.", "It is a show that you like to see on television.", "Это передача, которую вам нравится смотреть по телевизору."),
    ("prove", "You must prove that this is your bag.", "Show me that this thing really belongs to you.", "Покажи мне, что эта вещь действительно принадлежит тебе."),
    ("punish", "Parents sometimes punish their kids for bad behavior.", "They stop them from having fun because they were bad.", "Они лишают их веселья из-за плохого поведения."),
    ("put on", "It is cold, so put on your warm coat.", "Wear your jacket because it is cold outside.", "Надень куртку, потому что на улице холодно."),
    ("quarter", "I ate a quarter of the big cake.", "I ate one of four parts of the cake.", "Я съел одну из четырёх частей торта."),
    ("queen", "The queen lives in a very large palace.", "She is the most important woman in the country.", "Она самая главная женщина в стране."),
    ("quick", "He is very quick at his work.", "He does his work in a short time.", "Он делает свою работу за короткое время."),
    ("quickly", "Please walk quickly to the bus stop.", "Do it in a short amount of time.", "Сделайте это за короткое время."),
    ("quiet", "The library is a very quiet place.", "There is no noise in this room.", "В этой комнате совсем нет шума."),
    ("quit", "He wants to quit his job next month.", "He wants to stop doing this work.", "Он хочет перестать выполнять эту работу."),
    ("quite", "The weather is quite cold today.", "The weather is very cold but not too cold.", "Погода сегодня очень холодная, но не слишком."),
    ("race", "They watch the car race on Sunday.", "It is a game where people try to be the fastest.", "Это игра, где люди стараются быть самыми быстрыми."),
    ("raise", "Please raise your hand to answer the question.", "Move your hand up into the air.", "Поднимите руку вверх в воздух."),
    ("ran", "He ran to the park to see his friends.", "He moved very fast on his feet.", "Он очень быстро двигался на своих ногах."),
    ("rate", "The rate of speed is very high here.", "It is the level or speed of something.", "Это уровень или скорость чего-либо."),
    ("rather", "I would rather stay home and sleep today.", "I prefer to do this instead.", "Я предпочитаю сделать это вместо того."),
    ("reach", "Can you reach the book on the shelf?", "Can you touch it with your hand?", "Можете ли вы коснуться этого рукой?"),
    ("read", "I like to read books before I sleep.", "You look at words and understand the story.", "Вы смотрите на слова и понимаете историю."),
    ("really", "This pizza is really good.", "The food is very tasty.", "Еда очень вкусная."),
    ("record", "I want to record this song.", "You make a digital copy of the music.", "Ты делаешь цифровую копию музыки."),
    ("register", "You must register for the class.", "You sign up to join the group.", "Ты записываешься, чтобы присоединиться к группе."),
    ("relation", "They have a good relation.", "They are friendly with each other.", "Они дружелюбны друг к другу."),
    ("remain", "Please remain in your seat.", "Stay where you are sitting now.", "Оставайся там, где сидишь сейчас."),
    ("reply", "Did you reply to my email?", "Did you write an answer back?", "Ты написал ответ?"),
    ("responsible", "He is responsible for his dog.", "He takes care of his pet every day.", "Он заботится о своем питомце каждый день."),
    ("rock", "He found a big rock on the ground.", "It is a hard piece of stone.", "Это твердый кусок камня."),
    ("roll", "Watch the ball roll down the hill.", "The ball moves by turning over.", "Мяч движется, переворачиваясь."),
    ("root", "The tree has a long root.", "This part of the plant is under the ground.", "Эта часть растения находится под землей."),
    ("rope", "Use a rope to hold the box.", "You use this long string to tie things.", "Ты используешь эту длинную веревку, чтобы связать вещи."),
    ("rose", "She gave me a red rose.", "It is a beautiful flower with a sweet smell.", "Это красивый цветок с приятным запахом."),
    ("round", "The ball is very round.", "It has no corners and looks like a ball.", "У него нет углов, и оно похоже на мяч."),
    ("row", "We sit in the first row.", "People stand or sit in a line.", "Люди стоят или сидят в линию."),
    ("rub", "Rub your hands to keep warm.", "Move your hands back and forth against each other.", "Двигай руками туда-сюда друг о друга."),
    ("rule", "It is a rule to be quiet here.", "You must follow this instruction in this place.", "Ты должен следовать этой инструкции в этом месте."),
    ("run", "I like to run in the park.", "You move very fast using your legs.", "Ты движешься очень быстро, используя ноги."),
    ("run out", "We will run out of milk if we do not buy more.", "We will have zero milk left very soon.", "У нас скоро совсем не останется молока."),
    ("said", "He said that he was tired.", "He told me these words earlier.", "Он сказал мне эти слова ранее."),
    ("sat", "She sat on the chair.", "She was on the chair a moment ago.", "Она была на стуле минуту назад."),
    ("satisfy", "This simple meal will satisfy my hunger today.", "The food is enough and I feel good now.", "Еды достаточно, и я теперь чувствую себя хорошо."),
    ("saw", "I saw a big cat in the garden.", "My eyes looked at a big cat in the garden.", "Мои глаза посмотрели на большого кота в саду."),
    ("say", "Please say the word again for me.", "Please talk and tell me the word again.", "Пожалуйста, заговори и скажи мне это слово снова."),
    ("scale", "You should check your weight on the scale.", "Step on this tool to know how heavy you are.", "Встань на этот прибор, чтобы узнать, сколько ты весишь."),
    ("science", "I like to study science at school every day.", "You learn about how the world works in this class.", "На этом уроке ты узнаешь, как устроен мир."),
    ("scissors", "Please use scissors to cut this piece of paper.", "Take the tool with two blades to cut the paper.", "Возьми инструмент с двумя лезвиями, чтобы разрезать бумагу."),
    ("season", "Summer is a hot season for us.", "There are four parts of the year like winter or spring.", "Год делится на четыре части, например зиму или весну."),
    ("seat", "Please take a seat at the small table.", "Sit down on the chair by the small table.", "Присядь на стул у маленького столика."),
    ("secret", "I have a secret for you only.", "Do not tell anyone about this thing I tell you.", "Никому не рассказывай об этой вещи, которую я тебе сообщу."),
    ("see", "I can see the moon in the sky.", "My eyes look at the moon in the sky.", "Мои глаза смотрят на луну в небе."),
    ("see you later", "I must go now, see you later.", "I am leaving, we will talk again soon.", "Я ухожу, поговорим снова в ближайшее время."),
    ("sell", "They sell food in this small shop.", "You give money to a person to get things from them.", "Ты отдаешь человеку деньги, чтобы получить у него вещи."),
    ("send", "I will send a letter to my friend.", "I will post a letter to my friend today.", "Я отправлю письмо своему другу сегодня."),
    ("sense", "He has a good sense of humor.", "He understands jokes and makes people laugh.", "Он понимает шутки и заставляет людей смеяться."),
    ("sentence", "Please write a short sentence about your day.", "Write a few words that make a full thought.", "Напиши несколько слов, которые составляют полную мысль."),
    ("separate", "We need to separate the blue socks from the red ones.", "Put the blue socks in one place and the red ones in another.", "Положи синие носки в одно место, а красные в другое."),
    ("set", "I will set the alarm for seven o'clock.", "I will make the clock ready to ring at seven.", "Я подготовлю часы, чтобы они прозвенели в семь."),
    ("set up", "I need help to set up my new phone.", "I need help to prepare my device for use.", "Мне нужна помощь, чтобы подготовить новый телефон к работе."),
    ("seven", "I have seven books on my desk.", "I have one more than six books on my desk.", "У меня на столе на одну книгу больше, чем шесть."),
    ("several", "I have several apples in my bag.", "I have some apples, but not many.", "У меня есть несколько яблок, но не очень много."),
    ("shall", "Shall we go to the park now?", "Do you want to go to the park with me?", "Хочешь пойти со мной в парк?"),
    ("she", "She is my best friend at school.", "That girl is my best friend at school.", "Та девочка — мой лучший друг в школе."),
    ("sheet", "I need one clean sheet of paper to write a letter.", "You use a flat piece of paper for writing.", "Вы используете плоский кусок бумаги для письма."),
    ("shine", "The sun will shine very bright today.", "The sun gives a lot of light.", "Солнце дает много света."),
    ("shock", "It was a big shock to see him here.", "You feel very surprised by bad or strange news.", "Ты очень удивлен плохими или странными новостями."),
    ("shoe", "I buy a new shoe for my walk.", "You put this on your foot to go outside.", "Ты надеваешь это на ногу, чтобы выйти на улицу."),
    ("shoot", "They shoot at the target in the park.", "You use a gun to hit something far away.", "Ты используешь пистолет, чтобы попасть в цель вдалеке."),
    ("should", "You should drink more water every day.", "It is a good idea to do this.", "Было бы хорошо это сделать."),
    ("show", "Can you show me your new house?", "Help someone see something with their eyes.", "Помоги кому-то увидеть что-то своими глазами."),
    ("show up", "Will he show up at the party tonight?", "Will he arrive or appear at the event later?", "Он появится на вечеринке сегодня вечером?"),
    ("sight", "The mountain is a beautiful sight to see.", "It is something nice that you look at.", "Это что-то красивое, на что ты смотришь."),
    ("silver", "She has a small silver ring.", "This is a white metal for nice things.", "Это белый металл для красивых вещей."),
    ("simple", "The math test was very simple for me.", "It is not hard to do.", "Это несложно сделать."),
    ("since", "I have lived here since last year.", "From that time until now.", "С того времени и до сих пор."),
    ("sit", "Please sit on the chair and wait.", "Put your body on a chair.", "Расположи свое тело на стуле."),
    ("six", "There are six apples on the table.", "The number after five.", "Число, которое идет после пяти."),
    ("sky", "The sky is blue today.", "Look up and you see this over the world.", "Посмотри вверх, и ты увидишь это над миром."),
    ("sleep", "I want to sleep for eight hours tonight.", "You close your eyes and rest at night.", "Ты закрываешь глаза и отдыхаешь ночью."),
    ("slip", "Be careful not to slip on the wet floor.", "Your feet move and you almost fall down.", "Твои ноги проскальзывают, и ты почти падаешь."),
    ("smoke", "I see black smoke from the fire.", "This grey cloud comes from a hot fire.", "Это серое облако исходит от горячего огня."),
    ("soap", "Use soap to wash your hands well.", "You use this to get clean in the water.", "Ты используешь это, чтобы стать чистым в воде."),
    ("soil", "The plants grow well in this dark soil.", "The top layer of the ground where flowers grow.", "Верхний слой земли, где растут цветы."),
    ("some", "I want some water now.", "I need a small amount of water.", "Мне нужно немного воды."),
    ("soon", "The bus will be here soon.", "The bus is arriving in a very short time.", "Автобус приедет через очень короткое время."),
    ("sorry", "I am sorry for my mistake.", "Please do not be angry with me.", "Пожалуйста, не сердись на меня."),
    ("sounds good", "Let's eat pizza. Sounds good to me.", "That is a good idea, I like it.", "Это хорошая идея, мне нравится."),
    ("south", "My house is in the south.", "It is not the north of the map.", "Это не север на карте."),
    ("space", "The rocket travels into deep space.", "It flies far away from our planet.", "Она летит далеко от нашей планеты."),
    ("speak", "Can you speak English with me?", "Use your mouth to tell me words.", "Используй рот, чтобы сказать мне слова."),
    ("special", "Today is a special day for us.", "This day is not like other days.", "Этот день не такой, как другие."),
    ("speech", "The teacher gave a long speech today.", "She talked to everyone for a long time.", "Она долго разговаривала со всеми."),
    ("spell", "How do you spell your name?", "Tell me the letters in your name one by one.", "Назови мне буквы своего имени по порядку."),
    ("spoon", "Use a spoon to eat your soup.", "Use this metal tool to pick up liquid food.", "Используй этот металлический инструмент, чтобы зачерпнуть жидкую еду."),
    ("spring", "Flowers grow in the spring.", "This is the time after winter when the weather gets warm.", "Это время после зимы, когда становится тепло."),
    ("stage", "The actors are on the stage now.", "They are standing on the raised floor in the theater.", "Они стоят на возвышении в театре."),
    ("stand", "Please stand up when the music plays.", "Get up from your chair and be on your feet.", "Встань со своего стула и стой на ногах."),
    ("star", "I see a bright star in the sky.", "There is a small shining light in the night sky.", "В ночном небе виден маленький сияющий свет."),
    ("state", "The water is in a liquid state.", "It is a form of the water.", "Это форма воды."),
    ("steam", "Hot water makes a lot of steam.", "You see a white cloud coming from the boiling pot.", "Ты видишь белое облако, исходящее из кипящей кастрюли."),
    ("step", "Take one step to the left.", "Move your foot one time.", "Переставь ногу один раз."),
    ("stick", "The dog likes to carry a wooden stick.", "It is a thin piece of a tree on the ground.", "Это тонкий кусок дерева, лежащий на земле."),
    ("still", "He is still in the room.", "He is there and he does not leave.", "Он там и не уходит."),
    ("store", "I need to go to the food store.", "It is a place where you buy things to eat.", "Это место, где ты покупаешь еду."),
    ("straight", "The road goes straight to the city center.", "You do not turn left or right on this road.", "На этой дороге не нужно никуда сворачивать."),
    ("strange", "That man is very strange today.", "He is not like other people.", "Он не похож на других людей."),
    ("such", "It was such a nice day outside.", "The day was very good like that.", "День был очень хороший."),
    ("summer", "I love the hot summer sun.", "This is the warmest time of the year.", "Это самое жаркое время года."),
    ("supper", "We eat supper at seven o'clock.", "This is the meal you have in the evening.", "Это прием пищи вечером."),
    ("surface", "Put your pen on the table surface.", "This is the top part of the desk.", "Это верхняя часть стола."),
    ("system", "The new alarm system is very good.", "It is a group of parts working together.", "Это группа частей, работающих вместе."),
    ("take", "Please take your book from the bag.", "Hold the object and move it to you.", "Возьми предмет в руки."),
    ("take care", "Goodbye, please take care of yourself.", "Goodbye, be safe and stay healthy.", "До свидания, будь в безопасности и береги здоровье."),
    ("take off", "It is hot, so take off your coat.", "Put the clothes away from your body.", "Сними одежду, тебе станет легче."),
    ("tear", "Do not tear the old paper.", "You pull it apart into pieces.", "Ты разрываешь это на части."),
    ("telephone", "I talk to my mother on the telephone.", "You use this to call your friends.", "Ты используешь это, чтобы звонить друзьям."),
    ("television", "We watch a show on the television.", "You look at this to see movies at home.", "Ты смотришь на это, чтобы увидеть фильмы дома."),
    ("tell", "Can you tell me your name?", "Say some words to give me info.", "Произнеси слова, чтобы дать мне информацию."),
    ("ten", "I have ten apples in my basket.", "This number comes after nine.", "Это число идет после девяти."),
    ("term", "The school term ends in June.", "This is a fixed period of time for study.", "Это установленный период времени для учебы."),
    ("text", "Please read this short text now.", "These are words written on a page.", "Это слова, написанные на странице."),
    ("thank", "I want to thank you for help.", "Say you are happy because someone helped you.", "Скажи, что ты доволен, потому что тебе помогли."),
    ("that", "I know that he is here.", "This word points to a thing far away.", "Это слово указывает на предмет, который далеко."),
    ("the", "I see the cat on the bed.", "Use this word for one clear thing.", "Используй это слово для одного конкретного предмета."),
    ("the bill, please", "Could I have the bill, please?", "I want to pay for my food now.", "Я хочу заплатить за свою еду сейчас."),
    ("the menu, please", "The menu, please, I want to see the food.", "Give me the paper with the names of all the meals.", "Дайте мне бумагу с названиями всех блюд."),
    ("the room is too cold", "The room is too cold for me tonight.", "The air in here is not warm at all.", "Воздух здесь совсем не теплый."),
    ("their", "They like their new blue house.", "This shows that something belongs to them.", "Это показывает, что что-то принадлежит им."),
    ("them", "I see them in the park every day.", "I look at those people in the park every day.", "Я вижу этих людей в парке каждый день."),
    ("then", "I eat breakfast and then I go to work.", "After breakfast I go to work.", "После завтрака я иду на работу."),
    ("there", "My car is parked over there.", "My car is in that place.", "Моя машина находится в том месте."),
    ("these", "I really like these new shoes.", "I like the shoes that are near me.", "Мне нравятся туфли, которые рядом со мной."),
    ("they", "They are my best friends.", "My friends are very good people.", "Мои друзья — очень хорошие люди."),
    ("thing", "Please put that thing on the table.", "Put that object on the table.", "Положи этот предмет на стол."),
    ("think", "I think this book is very good.", "In my head, it is a great story.", "На мой взгляд, это отличная история."),
    ("third", "This is the third house on the street.", "This is the house after the second one.", "Это дом, который идет после второго."),
    ("this", "I want to buy this book.", "I want to buy the book here in my hand.", "Я хочу купить книгу, которую держу в руках."),
    ("those", "Look at those birds in the sky.", "Look at the birds far away in the sky.", "Посмотри на птиц вдалеке в небе."),
    ("though", "It is cold though the sun is out.", "It is cold but the sun is out.", "Холодно, но солнце светит."),
    ("thought", "He thought about the game all day long.", "The game was in his head all day.", "Он весь день не выходил у него из головы."),
    ("thousand", "The store has a thousand books.", "The store has ten times one hundred books.", "В магазине десять раз по сто книг."),
    ("three", "I have three apples in my bag.", "I have one plus two apples in my bag.", "У меня в сумке один плюс два яблока."),
    ("through", "We walk through the park to get home.", "We walk in one side of the park and out the other.", "Мы идем через парк, чтобы попасть домой."),
    ("title", "The title of the film is very long.", "The name of the film is very long.", "Название фильма очень длинное."),
    ("to", "I go to school every morning.", "My destination is school every morning.", "Мой пункт назначения каждое утро — школа."),
    ("together", "We study together in the library.", "We study at the same time in the same place.", "Мы учимся в одно время и в одном месте."),
    ("tonight", "I will see a movie tonight.", "I will see a movie this evening.", "Я посмотрю фильм этим вечером."),
    ("too", "I want to go there too.", "I also want to go there.", "Я тоже хочу пойти туда."),
    ("tool", "I need a tool to fix my bike.", "You use this thing to make or repair objects.", "Ты используешь эту вещь, чтобы что-то сделать или починить."),
    ("top", "The book is on the top of the desk.", "It is the highest part of something.", "Это самая высокая часть чего-либо."),
    ("total", "The total price for the meal is ten dollars.", "This is the final amount after you add everything.", "Это итоговая сумма, когда ты всё сложил вместе."),
    ("toward", "She walks toward the park every morning.", "She moves in the direction of that place.", "Она движется в сторону того места."),
    ("track", "We run on the track at the school.", "This is a special path for people to run on.", "Это специальная дорожка, по которой люди бегают."),
    ("trouble", "I am in big trouble because I forgot my homework.", "You are in a bad state and have problems.", "Ты в плохом положении и у тебя возникли проблемы."),
    ("turn off", "Please turn off the light in the room.", "Stop the lamp, it is dark now.", "Выключи лампу, теперь темно."),
    ("turn on", "Please turn on the light in the dark room.", "Make the lamp work to have some light.", "Заставь лампу работать, чтобы стало светло."),
    ("turn right", "You must turn right at the park.", "Go to the hand you use to write.", "Иди в сторону руки, которой пишешь."),
    ("twelve", "I have twelve apples in my big basket.", "This number comes after eleven and before thirteen.", "Это число идет после одиннадцати и перед тринадцатью."),
    ("twenty", "She is twenty years old today.", "This number is two times ten.", "Это число, которое равно десяти, умноженному на два."),
    ("two", "I have two dogs in my house.", "This is the number after one.", "Это число, которое идет после одного."),
    ("type", "Please type your name on the computer screen.", "Use your fingers to write letters on a keyboard.", "Используй пальцы, чтобы написать буквы на клавиатуре."),
    ("under", "The cat is sleeping under the table.", "It is below something else.", "Это находится внизу под чем-то другим."),
    ("understand", "I understand your words very well.", "You know the meaning of what someone says.", "Ты знаешь значение того, что кто-то говорит."),
    ("unit", "Each unit in this house has a kitchen.", "It is one part of a big group.", "Это одна часть большой группы."),
    ("universe", "The universe is very big and old.", "This includes all stars, planets, and space.", "Это всё, что включает звезды, планеты и космос."),
    ("until", "I will wait here until you come back.", "Stay in this place up to the time you return.", "Оставайся здесь до тех пор, пока не вернешься."),
    ("up", "Please look up at the bright sun.", "Move your eyes to a higher place.", "Переведи взгляд на более высокое место."),
    ("upon", "He sat upon the big wooden chair.", "He is now in a position on top of something.", "Он находится в положении сверху на чем-то."),
    ("vacation", "We go on vacation to the sea in summer.", "This is a time when you do not go to work.", "Это время, когда ты не ходишь на работу."),
    ("very", "It is a very hot day today.", "You use this to make an adjective stronger.", "Ты используешь это, чтобы сделать прилагательное более сильным."),
    ("wake up", "I wake up at seven every morning.", "Open your eyes and start your day.", "Открой глаза и начинай свой день."),
    ("water, please", "Some water, please, I am thirsty.", "I want a clear drink that is not juice.", "Я хочу прозрачный напиток, который не является соком."),
    ("way", "Can you show me the way to the park?", "Tell me how I can get to the park.", "Скажи мне, как добраться до парка."),
    ("welcome", "You are welcome to my house today.", "Please come inside and be my guest.", "Пожалуйста, заходи, будь моим гостем."),
    ("well", "She speaks English very well.", "She can talk in this language in a good way.", "Она может говорить на этом языке хорошо."),
    ("west", "The sun sets in the west.", "It is the place where the day ends.", "Это место, где заканчивается день."),
    ("what", "What is your name?", "Tell me the word for your identity.", "Скажи мне слово, которым тебя называют."),
    ("when", "When do you go to bed?", "At what time do you sleep at night?", "В какое время ты ложишься спать ночью?"),
    ("where", "Where is my blue bag?", "In what place can I find my item?", "В каком месте я могу найти свою вещь?"),
    ("which", "Which apple do you want?", "Choose one of these pieces of fruit.", "Выбери один из этих фруктов."),
    ("while", "I read while he cooks dinner.", "I do this at the same time he is making food.", "Я делаю это в то же самое время, когда он готовит еду."),
    ("who", "Who is that tall man?", "What is the name of that person?", "Как зовут того человека?"),
    ("will", "I will call you tomorrow.", "I plan to do this action in the future.", "Я планирую сделать это действие в будущем."),
    ("wine", "He likes to drink red wine at dinner.", "This is a red or white drink from grapes.", "Это красный или белый напиток из винограда."),
    ("winter", "It is cold in winter.", "This is the season with snow and ice.", "Это время года со снегом и льдом."),
    ("with", "I want to go to the park with you.", "You and I go to the park together.", "Ты и я идем в парк вместе."),
    ("write", "I write a letter to my mom.", "Use a pen to put words on paper.", "Используй ручку, чтобы оставить слова на бумаге."),
    ("yet", "The bus is not here yet.", "It has not arrived up to this moment.", "Он не приехал к этому моменту."),
    ("you", "You are a very good student.", "I am talking to the person in front of me.", "Я говорю с человеком, который передо мной."),
    ("yourself", "You should cook dinner for yourself today.", "Make food for you, not for other people.", "Приготовь еду для себя, а не для других."),
]


def upgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET"
        "  example_sentence = COALESCE(NULLIF(example_sentence, ''), :sentence),"
        "  abstract_example_en = COALESCE(abstract_example_en, :hint_en),"
        "  abstract_example_ru = COALESCE(abstract_example_ru, :hint_ru) "
        "WHERE track = 'en' AND normalized_word = :n"
    )
    for n, sentence, hint_en, hint_ru in EXAMPLES:
        conn.execute(stmt, {"n": n, "sentence": sentence, "hint_en": hint_en, "hint_ru": hint_ru})


def downgrade() -> None:
    conn = op.get_bind()
    stmt = sa.text(
        "UPDATE words SET example_sentence = NULL,"
        "  abstract_example_en = NULL, abstract_example_ru = NULL "
        "WHERE track = 'en' AND normalized_word = :n AND example_sentence = :sentence"
    )
    for n, sentence, _hint_en, _hint_ru in EXAMPLES:
        conn.execute(stmt, {"n": n, "sentence": sentence})
