"""The 160 most common English words the catalogue simply did not have.

Matching the catalogue against the New General Service List found that we cover
54% of it, and that the holes are at the top: `would` is the 36th most common
word in English and was absent, while `giggle`, `frown` and `gaze` were in
active rotation for an A1 learner. 171 of the first thousand were missing.

Eleven of those are dropped rather than added: `accord`, `regard` and `due`
only really occur inside phrases («according to»), `therefore`, `thus` and
`whatever` are connectives that grammar owns, `throughout` and `below` are
prepositions, `yeah` has nothing to translate, `unclear` is a corpus artefact
and `cent` duplicates `percent`. That leaves 149.

Every entry was generated offline and mechanically verified before landing
here: the translation must be a short Russian gloss with no Latin in it (it is
shown as a quiz option, so an English letter would hand over the answer), and
the example must contain the word in a form the bot's cloze masker can blank,
leave enough context to infer it, and use no vocabulary above the word's own
level. Hints are checked for not containing the answer.

Two thirds of these are business and news vocabulary — `organization`,
`investment`, `economic`. That is the corpus talking: NGSL is built on general
*written* English. They are graded B1-B2 and the level ceiling holds them back
until the learner is ready, which is exactly what the ceiling is for.

`polysemous` marks the 37 words whose senses are unrelated enough that a
one-translation card teaches one sense as if it were the whole word (`charge`,
`stock`, `firm`). They are kept because they are genuinely frequent, and the
flag lets the queue prefer unambiguous words of the same band first.

Revision ID: 0047
Revises: 0046
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0047"
down_revision = "0046"
branch_labels = None
depends_on = None

# (writing, translation, level, ngsl_rank, polysemous, example, hint_en, hint_ru)
WORDS: tuple[tuple, ...] = (
    ("company", "компания / общество", "A1", 107, True, "He works at a big car company.",
     "He works at a large business with many people.", "Он работает в крупной фирме, где много сотрудников."),
    ("lot", "много / участок / лот", "A1", 123, True, "I have a lot of books at home.",
     "I have many books at home.", "У меня дома очень много книг."),
    ("something", "что-то", "A1", 138, False, "I want to eat something tasty.",
     "I want to eat a thing that is good.", "Я хочу съесть какую-нибудь вкусную вещь."),
    ("information", "информация / сведения", "A2", 213, False, "Please give me more information about the trip.",
     "Please tell me more facts about the trip.", "Пожалуйста, расскажи мне больше фактов о поездке."),
    ("government", "правительство", "A2", 216, False, "The government makes new laws for the country.",
     "The group of people who lead the country make new laws.", "Группа людей, руководящая страной, принимает новые законы."),
    ("service", "обслуживание / услуга", "A2", 223, False, "The service at this small cafe is very good.",
     "The people who work there help you in a nice way.", "Люди, которые там работают, помогают вам очень вежливо."),
    ("example", "пример / образец", "A1", 235, False, "Can you give me an example of a fruit?",
     "Can you show me one thing that is a fruit?", "Можешь привести один объект в качестве примера фрукта?"),
    ("member", "член / участник", "A2", 266, False, "He is a new member of the club.",
     "He is a new person in this group.", "Он новый человек в этой группе."),
    ("whole", "целый / весь", "A2", 310, False, "I ate the whole cake by myself.",
     "I ate all of the cake by myself.", "Я съел весь торт целиком в одиночку."),
    ("sort", "сорт / вид / сортировать", "A2", 316, True, "What sort of music do you like?",
     "What kind of music do you like?", "Какой вид музыки тебе нравится?"),
    ("base", "база / основание", "A2", 327, True, "This is the base of the lamp.",
     "This is the bottom part of the lamp.", "Это нижняя часть лампы."),
    ("center", "центр / середина", "A1", 334, False, "The park is in the center of the city.",
     "You can find this place right in the heart of town.", "Вы можете найти это место прямо в самом сердце города."),
    ("future", "будущее", "A1", 370, False, "I want to be a doctor in the future.",
     "I want to be a doctor in the time that is coming.", "Я хочу стать врачом в то время, которое скоро наступит."),
    ("history", "история", "A2", 385, False, "I like to read about world history.",
     "I like to read about things that happened in the past.", "Мне нравится читать о событиях, которые произошли в прошлом."),
    ("political", "политический", "B1", 394, False, "They have many political ideas for the country.",
     "They have many ideas about how to rule the country.", "У них есть много идей о том, как управлять страной."),
    ("sale", "продажа / распродажа", "A2", 398, False, "This shirt was on sale yesterday.",
     "This shirt had a lower price yesterday.", "На эту рубашку вчера была скидка."),
    ("general", "общий / главный", "B1", 404, True, "This is a general rule for everyone.",
     "This is a common rule for all people.", "Это общее правило для всех людей."),
    ("individual", "индивидуальный / личность", "B1", 409, True, "Every individual has their own dream.",
     "Every single person has their own dream.", "У каждого отдельного человека есть своя мечта."),
    ("staff", "персонал / сотрудники", "B1", 431, False, "The hotel staff is very kind.",
     "The people who work at the hotel are very kind.", "Люди, которые работают в отеле, очень добрые."),
    ("activity", "деятельность / активность", "A2", 432, False, "Swimming is my favorite summer activity.",
     "Swimming is the thing I like to do most in summer.", "Плавание — это занятие, которое я больше всего люблю летом."),
    ("war", "война", "A2", 435, False, "The war is bad for all people.",
     "It is a long fight between two countries.", "Это долгая борьба между двумя странами."),
    ("someone", "кто-то", "A1", 439, False, "Someone is at the door right now.",
     "A person is there, but you do not know who.", "Там есть какой-то человек, но ты не знаешь кто."),
    ("condition", "условие / состояние", "B1", 445, True, "The old car is in a bad condition.",
     "The car is not good and needs help.", "Машина не в порядке и нуждается в починке."),
    ("community", "сообщество / община", "B1", 465, False, "Our community helps the people in need.",
     "A group of people living together in one place.", "Группа людей, живущих вместе в одном месте."),
    ("action", "действие / поступок", "A2", 474, False, "It is time for action now.",
     "You need to do something right away.", "Тебе нужно сделать что-то прямо сейчас."),
    ("model", "модель / образец", "A2", 485, False, "She is a model for young girls.",
     "She is a good person to look at and follow.", "Она хороший человек, на которого стоит равняться."),
    ("customer", "клиент / покупатель", "A1", 487, False, "The customer wants to buy this red shirt.",
     "A person who buys things in a shop.", "Человек, который покупает вещи в магазине."),
    ("economic", "экономический", "B1", 493, False, "The economic situation is hard this year.",
     "It is about money and how we use it.", "Это касается денег и того, как мы их используем."),
    ("site", "место / сайт", "A2", 494, False, "This site is great for finding new jobs.",
     "A place on the internet to look for information.", "Место в интернете для поиска информации."),
    ("charge", "заряд / плата / обвинение", "B1", 498, True, "Do they charge money for the bag?",
     "Do you need to pay to get it?", "Нужно ли тебе платить, чтобы получить это?"),
    ("organization", "организация", "B1", 512, False, "This organization helps poor children every day.",
     "A group of people working for one goal.", "Группа людей, работающих ради одной цели."),
    ("fund", "фонд / финансировать", "B2", 527, True, "They will fund the new park project.",
     "They will give money to help it start.", "Они дадут деньги, чтобы помочь этому начаться."),
    ("industry", "промышленность / отрасль", "B1", 530, False, "The car industry is very big today.",
     "Many companies that make the same type of things.", "Много компаний, которые производят одинаковые вещи."),
    ("education", "образование", "A2", 531, False, "Good education is important for your future.",
     "Learning things at school or college.", "Обучение чему-либо в школе или колледже."),
    ("likely", "вероятный", "B1", 535, False, "It is likely to rain later today.",
     "It will probably happen soon.", "Это, скорее всего, случится скоро."),
    ("certainly", "безусловно / конечно", "B1", 536, False, "I will certainly be there at five.",
     "I promise it will happen for sure.", "Я обещаю, что это точно произойдет."),
    ("national", "национальный / государственный", "B1", 537, False, "This is a national holiday in my country.",
     "It is for the whole country, not just one city.", "Это для всей страны, а не только для одного города."),
    ("security", "безопасность / охрана", "B1", 541, False, "The police work for our security.",
     "They make sure that we are safe.", "Они следят за тем, чтобы мы были в безопасности."),
    ("standard", "стандарт / норма", "B1", 547, False, "This is the standard for all our work.",
     "The way things must look or be done.", "То, как вещи должны выглядеть или делаться."),
    ("vote", "голос / голосовать", "A2", 548, False, "You can vote for your favorite person.",
     "You choose someone you want to lead.", "Ты выбираешь того, кого хочешь видеть лидером."),
    ("percent", "процент", "A2", 549, False, "Ten percent of the students are absent today.",
     "One part of a hundred is missing from class.", "Одна сотая часть учеников сегодня отсутствует."),
    ("address", "адрес / обращение", "A2", 558, True, "Please write your home address on this paper.",
     "Tell me the street and house where you live.", "Напиши улицу и номер дома, где ты живешь."),
    ("performance", "производительность / выступление", "B1", 559, True, "The band gave a great performance last night.",
     "The musicians played music for a large crowd.", "Музыканты играли для большой толпы вчера вечером."),
    ("technology", "технология", "A2", 563, False, "Modern technology makes our daily life very easy.",
     "New machines and computers help us every day.", "Новые машины и компьютеры помогают нам каждый день."),
    ("culture", "культура", "A2", 568, False, "I want to learn about Japanese culture.",
     "People there have unique traditions and habits.", "У этих людей уникальные традиции и привычки."),
    ("material", "материал / вещество", "A2", 571, False, "This soft material is good for a blanket.",
     "You use this fabric to make clothes.", "Ты используешь эту ткань, чтобы делать одежду."),
    ("limit", "предел / ограничение", "B1", 572, False, "There is a speed limit on this road.",
     "You cannot drive faster than this number.", "Ты не можешь ехать быстрее, чем разрешено."),
    ("century", "век / столетие", "A2", 591, False, "This old house is from the last century.",
     "It is one hundred years old.", "Этому зданию уже сто лет."),
    ("former", "бывший / прежний", "B1", 599, False, "My former teacher is a very kind person.",
     "This is the teacher I had before.", "Это учитель, который был у меня раньше."),
    ("contact", "контакт / связь", "A2", 600, False, "Please keep in contact with your old friends.",
     "Send messages and talk to them often.", "Пиши им сообщения и общайся с ними часто."),
    ("particularly", "особенно / в частности", "B1", 601, False, "I particularly like the blue dress you wear.",
     "I like this one more than the others.", "Это платье мне нравится больше остальных."),
    ("response", "ответ / реакция", "A2", 606, False, "I am waiting for a response to my letter.",
     "I want to get an answer back soon.", "Я хочу получить ответ в ближайшее время."),
    ("suppose", "полагать / предполагать", "A2", 610, False, "I suppose it will rain later today.",
     "I think the weather will change soon.", "Я думаю, погода скоро изменится."),
    ("court", "суд / корт", "A2", 615, True, "They play tennis on the school court.",
     "This is the place where people play sports.", "Это место, где люди занимаются спортом."),
    ("simply", "просто / элементарно", "A2", 626, False, "The task is simply too hard for me.",
     "It is just very difficult to do.", "Это просто очень сложно сделать."),
    ("firm", "фирма / твердый", "B1", 628, True, "The bed has a firm mattress for sleep.",
     "It is not soft, it is hard.", "Он не мягкий, он твердый."),
    ("article", "статья / предмет", "A2", 630, True, "I read an interesting article in the paper.",
     "It is a short story about news.", "Это короткий текст с новостями."),
    ("recently", "недавно", "A2", 638, False, "I recently bought a new pair of shoes.",
     "I did this a short time ago.", "Я сделал это совсем недавно."),
    ("financial", "финансовый", "B1", 644, False, "He needs financial help for his business.",
     "He needs money to run his shop.", "Ему нужны деньги для ведения бизнеса."),
    ("art", "искусство", "A1", 646, False, "She likes to look at art in museums.",
     "She enjoys beautiful paintings and drawings.", "Ей нравятся красивые картины и рисунки."),
    ("pause", "пауза / приостановка", "B1", 649, False, "We take a short pause during our long work.",
     "We stop for a small break in our work.", "Мы делаем небольшой перерыв в работе."),
    ("international", "международный", "A2", 662, False, "This is an international airport for many people.",
     "Many people from different countries use this place.", "Люди из разных стран пользуются этим местом."),
    ("worker", "рабочий / работник", "A1", 673, False, "The worker is in the factory today.",
     "The man who has a job is at the factory.", "Человек, у которого есть работа, находится на заводе."),
    ("necessary", "необходимый", "A2", 676, False, "Water is necessary for all plants in the garden.",
     "You must have it to keep them healthy.", "Тебе нужно иметь это, чтобы они оставались здоровыми."),
    ("medium", "средний / средство / среда", "B1", 689, True, "I want a medium shirt, not big or small.",
     "I need a size that is not large and not small.", "Мне нужен размер, который не большой и не маленький."),
    ("stock", "запас / акции", "B2", 691, True, "The shop has a large stock of apples.",
     "The store keeps a lot of food ready to sell.", "В магазине много продуктов, готовых к продаже."),
    ("management", "управление / менеджмент", "B1", 692, False, "Good management helps the team work well.",
     "The way a boss leads the team is important.", "То, как начальник руководит командой, очень важно."),
    ("character", "характер / персонаж / символ", "B1", 693, True, "He is my favorite character in the book.",
     "He is a person in the story I like.", "Он персонаж в книге, который мне нравится."),
    ("final", "финальный / окончательный", "A2", 698, False, "This is the final game of the year.",
     "This is the last game before it ends.", "Это последняя игра перед окончанием."),
    ("economy", "экономика", "B1", 699, False, "The world economy is very important today.",
     "The system of money and trade in the world.", "Система денег и торговли в мире."),
    ("image", "образ / изображение", "A2", 704, False, "I see a nice image on the screen.",
     "I look at a picture on the screen.", "Я смотрю на картинку на экране."),
    ("addition", "дополнение / сложение", "B1", 707, False, "In addition, we need to buy some milk.",
     "Also, we should get some milk too.", "Также нам нужно купить немного молока."),
    ("population", "население", "B1", 710, False, "The city has a large population of people.",
     "Many people live in this big city.", "В этом большом городе живет много людей."),
    ("fail", "терпеть неудачу / провалиться", "A2", 711, False, "I do not want to fail my math test today.",
     "I hope I do not get a bad mark.", "Надеюсь, я не получу плохую оценку."),
    ("production", "производство", "B1", 713, False, "The production of cars is very fast now.",
     "Making new cars is a very fast process.", "Создание новых машин сейчас идет очень быстро."),
    ("drug", "лекарство / наркотик", "A2", 721, True, "The doctor gives me some drug for my cold.",
     "I take medicine to feel better.", "Я принимаю лекарство, чтобы почувствовать себя лучше."),
    ("series", "серия / ряд", "B1", 723, False, "I watch a new series on TV tonight.",
     "I watch one part of a long show.", "Я смотрю одну часть длинного шоу."),
    ("direct", "прямой / направлять", "B1", 724, True, "Can you direct me to the train station?",
     "Can you show me the way to the station?", "Можешь показать мне дорогу до станции?"),
    ("director", "директор / режиссер", "B1", 727, False, "The director says action to the actors.",
     "The person who leads the movie tells people what to do.", "Человек, который руководит съемками фильма, говорит людям, что делать."),
    ("clearly", "ясно / четко", "A2", 728, False, "Please speak clearly so I can hear you.",
     "Talk in a way that is easy to understand.", "Говори так, чтобы тебя было легко понять."),
    ("depend", "зависеть", "A2", 731, False, "My plans depend on the weather today.",
     "What I do later is based on if it is sunny or rainy.", "То, что я буду делать позже, зависит от того, будет ли солнечно или дождливо."),
    ("department", "отдел / департамент", "B1", 736, False, "She works in the sales department at this office.",
     "This is a specific section of a large company.", "Это конкретный сектор в большой компании."),
    ("gain", "получать / прирост", "B1", 737, False, "You will gain a lot of new knowledge here.",
     "You will get more information by studying.", "Ты получишь больше знаний, изучая что-то."),
    ("church", "церковь", "A2", 744, False, "They go to the old church every Sunday morning.",
     "This is a place where people pray to God.", "Это место, где люди молятся Богу."),
    ("item", "предмет / пункт", "B1", 747, False, "I have one more item to buy today.",
     "I need to purchase another thing at the store.", "Мне нужно купить еще одну вещь в магазине."),
    ("stuff", "вещи / материал", "A2", 752, True, "Please put all your stuff in this big box.",
     "Move all the things that belong to you into this container.", "Сложи все свои вещи в эту коробку."),
    ("election", "выборы", "B1", 757, False, "People vote for a new leader during an election.",
     "This is the time when citizens choose their new president.", "Это время, когда граждане выбирают нового президента."),
    ("military", "военный", "B1", 758, False, "He decided to join the military last year.",
     "He went to serve in the army and protect his country.", "Он пошел служить в армию, чтобы защищать свою страну."),
    ("club", "клуб / дубинка", "A1", 760, True, "I go to a sports club every Friday night.",
     "I go to a place where people play games together every Friday.", "Я хожу в место, где люди вместе играют в игры каждую пятницу."),
    ("discussion", "обсуждение / дискуссия", "B1", 764, False, "The discussion about our plans was very helpful.",
     "Talking about our ideas together helped us a lot.", "Совместное обсуждение наших идей очень нам помогло."),
    ("statement", "заявление / утверждение", "B1", 769, False, "The police made a short statement about the accident.",
     "They gave a formal report with information about what happened.", "Они дали официальный отчет с информацией о том, что случилось."),
    ("link", "ссылка / связь", "B1", 770, False, "Click this link to open the website page.",
     "Use this connection to go to another part of the internet.", "Используй это соединение, чтобы перейти в другую часть интернета."),
    ("strike", "удар / забастовка", "B1", 776, True, "The workers started a strike for better pay.",
     "People stopped working to show they are unhappy with their salary.", "Люди перестали работать, чтобы показать, что они недовольны зарплатой."),
    ("agreement", "соглашение / договор", "B1", 785, False, "Both sides signed the agreement this morning.",
     "They made a deal and wrote it down on paper.", "Они заключили сделку и записали её на бумаге."),
    ("capital", "столица / капитал", "B1", 789, True, "Paris is the capital of France.",
     "This is the most important city in the country.", "Это самый важный город в стране."),
    ("target", "цель / мишень", "B1", 797, False, "He tried to hit the target with an arrow.",
     "He tried to shoot at the object he wanted to hit.", "Он пытался попасть в предмет, в который хотел выстрелить."),
    ("access", "доступ", "B1", 802, False, "Do you have access to the private files?",
     "Are you allowed to open and see these documents?", "Тебе разрешено открывать и смотреть эти документы?"),
    ("movement", "движение", "B1", 803, False, "I saw a sudden movement near the door.",
     "Something changed its place very quickly.", "Что-то очень быстро изменило свое местоположение."),
    ("loss", "потеря / убыток", "B1", 806, False, "The family felt great loss after the fire.",
     "They had a sad time because they lost many things.", "Им было тяжело, потому что они потеряли много вещей."),
    ("pressure", "давление", "B1", 809, False, "The pressure in the pipe is too high.",
     "There is a strong force pushing against the walls of the pipe.", "Сильная сила давит на стенки трубы."),
    ("conference", "конференция / совещание", "B1", 812, False, "I have to attend a business conference in London next week.",
     "I need to go to a big meeting with many people to talk about work.", "Мне нужно пойти на большую встречу со множеством людей, чтобы обсудить работу."),
    ("investment", "инвестиция / вложение", "B2", 822, False, "This company needs a big investment to grow and build more shops.",
     "The business needs a lot of money to become larger and better.", "Бизнесу нужно много денег, чтобы стать больше и лучше."),
    ("organize", "организовывать", "B1", 824, False, "She likes to organize parties for all her friends at home.",
     "She likes to plan and prepare everything for a fun event.", "Ей нравится планировать и готовить всё для веселого мероприятия."),
    ("advance", "продвижение / успех / аванс", "B2", 844, True, "The team made a great advance in the study this month.",
     "The group moved forward and got better results in their work.", "Группа продвинулась вперед и получила лучшие результаты в своей работе."),
    ("generally", "обычно / в основном", "B1", 848, False, "I generally drink coffee in the morning before I go to work.",
     "Most of the time, I have a cup of coffee after I wake up.", "В большинстве случаев я пью чашку кофе после того, как просыпаюсь."),
    ("operation", "операция / работа / действие", "B2", 849, True, "The doctor says the operation will take about two hours today.",
     "The medical procedure to fix his health will happen in the hospital.", "Медицинская процедура для поправки его здоровья пройдет в больнице."),
    ("associate", "ассоциировать / связывать / коллега", "B2", 857, True, "Do you associate this song with your happy childhood memories?",
     "Does this music make you think about your time as a child?", "Заставляет ли эта музыка тебя вспоминать время, когда ты был ребенком?"),
    ("positive", "положительный / уверенный", "A2", 859, True, "She has a positive view of her new job.",
     "She thinks good things about her work.", "Она думает о своей работе в хорошем ключе."),
    ("style", "стиль / фасон", "A2", 865, False, "I really like the style of this red dress.",
     "I like the way this red dress looks.", "Мне нравится, как выглядит это красное платье."),
    ("refer", "ссылаться / относиться", "B2", 866, False, "Please refer to the page number for more information on this.",
     "Look at the page number to find more details about this topic.", "Посмотри на номер страницы, чтобы найти больше деталей об этой теме."),
    ("successful", "успешный", "A2", 872, False, "He is a very successful man because he works very hard.",
     "He does his job very well and achieves all his goals.", "Он очень хорошо делает свою работу и достигает всех своих целей."),
    ("competition", "соревнование / конкуренция", "B1", 875, False, "They will join a swimming competition at the local sports club.",
     "They will take part in a game to see who is the fastest swimmer.", "Они примут участие в игре, чтобы узнать, кто самый быстрый пловец."),
    ("reference", "ссылка / рекомендация / справка", "B2", 878, True, "I asked my boss for a good reference for my new job.",
     "I asked a person to write a letter saying I am a good worker.", "Я попросил человека написать письмо о том, что я хороший работник."),
    ("argument", "аргумент / спор", "B1", 879, False, "They had a long argument about which movie to watch tonight.",
     "They talked in a loud way because they did not agree on a film.", "Они громко спорили, потому что не могли договориться о фильме."),
    ("adult", "взрослый", "A2", 880, False, "Every adult needs to pay for food and a place to live.",
     "Every person who is not a child must take care of themselves.", "Каждый человек, который уже не ребенок, должен заботиться о себе сам."),
    ("document", "документ / документировать", "B1", 882, True, "Please read this important document before you sign your name here.",
     "Read this formal paper with information before you put your name on it.", "Прочитай эту официальную бумагу с информацией, прежде чем поставить на ней свою подпись."),
    ("pattern", "шаблон / узор / модель", "B1", 883, False, "This shirt has a blue pattern with small white flowers on it.",
     "The clothes have a repeating design of flowers on the fabric.", "На одежде есть повторяющийся рисунок цветов на ткани."),
    ("application", "заявление / приложение / применение", "B2", 884, True, "You need to send your application to the office by Friday.",
     "You must send your form to ask for a job or a place at school.", "Ты должен отправить свою анкету, чтобы попросить о работе или месте в школе."),
    ("central", "центральный", "B1", 891, False, "The hotel is in a central part of the big city.",
     "The building is in the middle of the town near all shops.", "Здание находится в середине города рядом со всеми магазинами."),
    ("career", "карьера", "A2", 892, False, "He wants to start a career in music.",
     "He wants to do this work for a long time.", "Он хочет заниматься этим делом долгое время."),
    ("officer", "офицер / чиновник / сотрудник", "B2", 896, True, "The police officer helps people in the city street.",
     "A person who works for the police and keeps order.", "Человек, который работает в полиции и следит за порядком."),
    ("author", "автор", "A2", 910, False, "The author writes a new book every year.",
     "A person who creates stories or books.", "Человек, который создает истории или пишет книги."),
    ("male", "мужской", "A2", 914, False, "The male lion has a very big head.",
     "Not female; a man or a boy animal.", "Не женского пола; мужчина или животное мужского пола."),
    ("operate", "управлять / работать / оперировать", "B2", 915, True, "He can operate this big machine very well.",
     "To make a machine work or control it.", "Заставлять машину работать или управлять ею."),
    ("exercise", "упражнение / тренировка / осуществление", "A2", 917, True, "I do a short exercise every morning in my room.",
     "You move your body to stay strong and healthy.", "Ты двигаешься, чтобы оставаться сильным и здоровым."),
    ("useful", "полезный", "A1", 918, False, "This pen is very useful for my work.",
     "It helps you do things in a good way.", "Это помогает тебе делать дела хорошо."),
    ("property", "собственность / свойство", "B1", 921, True, "This big house is his private property.",
     "Something that belongs to a person.", "То, что принадлежит человеку."),
    ("newspaper", "газета", "A1", 929, False, "My father reads the newspaper at the table.",
     "It is a paper with news about the world.", "Это бумага с новостями о мире."),
    ("everybody", "все / каждый", "A1", 933, False, "Everybody likes to eat cake at the party.",
     "All the people are happy to eat food.", "Все люди рады поесть."),
    ("professional", "профессиональный", "B1", 936, False, "She is a professional player in this sport.",
     "Someone who gets paid to do a job well.", "Тот, кому платят за хорошую работу."),
    ("object", "предмет / объект / возражать", "A2", 942, True, "I see a strange object on the table.",
     "A thing that you can touch or see.", "Вещь, которую можно потрогать или увидеть."),
    ("credit", "кредит / доверие / зачет", "B1", 944, True, "He needs some credit to buy a car.",
     "Money that a bank gives you to pay back later.", "Деньги, которые дает банк, чтобы вернуть их позже."),
    ("extend", "расширять / продлевать", "B2", 950, False, "They want to extend the road to the sea.",
     "To make something longer or bigger.", "Сделать что-то длиннее или больше."),
    ("possibility", "возможность", "B1", 951, False, "There is a possibility of rain today.",
     "A chance that something can happen.", "Шанс, что что-то может произойти."),
    ("facility", "объект / удобство / сооружение", "B2", 953, True, "The sports facility has a large swimming pool.",
     "A place built for a special activity.", "Место, построенное для специального занятия."),
    ("variety", "разнообразие / вид", "B1", 954, False, "The shop has a great variety of fruit.",
     "Many different types of the same thing.", "Много разных видов одного и того же."),
    ("female", "женский / самка", "A2", 961, False, "She is a female student at this school.",
     "Not male; a woman or a girl animal.", "Не мужского пола; женщина или животное женского пола."),
    ("original", "оригинальный / первоначальный", "B1", 963, False, "This is an original idea for our project.",
     "New and different from everything else.", "Новое и отличающееся от всего остального."),
    ("agency", "агентство", "B1", 970, False, "I work for a travel agency in town.",
     "A business that helps people do something.", "Бизнес, который помогает людям что-то делать."),
    ("dollar", "доллар", "A1", 971, False, "The toy costs only one dollar.",
     "The money used in the USA.", "Деньги, которые используют в США."),
    ("candidate", "кандидат", "B1", 977, False, "The candidate wants a new job at this company.",
     "This person is applying for a position.", "Этот человек подает заявку на должность."),
    ("proposal", "предложение", "B2", 980, False, "He has a great proposal for our business project.",
     "He has a plan that he wants to show you.", "У него есть план, который он хочет вам показать."),
    ("somebody", "кто-то", "A1", 983, False, "Somebody is at the front door right now.",
     "A person is there, but you do not know who.", "Там какой-то человек, но вы не знаете кто."),
    ("magazine", "журнал", "A1", 985, False, "I like reading this fashion magazine every month.",
     "It is a book with many pictures and news.", "Это книга с множеством картинок и новостей."),
    ("communication", "общение / связь", "B1", 991, False, "Good communication is important for a happy team.",
     "Talking and sharing ideas helps the group work well.", "Разговоры и обмен идеями помогают группе хорошо работать."),
    ("agent", "агент / представитель", "B1", 992, False, "The travel agent helps us book our summer trip.",
     "This person works to organize holidays for other people.", "Этот человек работает, чтобы организовывать отдых для других людей."),
    ("traditional", "традиционный", "B1", 993, False, "They eat a traditional meal on this special day.",
     "It is a way of doing things from the past.", "Это способ делать вещи, который пришел из прошлого."),
    ("suddenly", "внезапно", "A2", 997, False, "The light suddenly went out in the dark room.",
     "It happened very fast and you did not expect it.", "Это случилось очень быстро, и вы этого не ожидали."),
    ("generation", "поколение", "B1", 998, False, "Our generation likes to use computers and phones.",
     "All the people born at about the same time.", "Все люди, рожденные примерно в одно время."),)


def upgrade() -> None:
    op.add_column(
        "words",
        sa.Column("polysemous", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.get_bind().execute(
        sa.text(
            "INSERT INTO words (track, writing, normalized_word, translation, level,"
            " ngsl_rank, polysemous, example_sentence, abstract_example_en,"
            " abstract_example_ru, is_function_word)"
            " VALUES ('en', :w, :norm, :t, :lvl, :rank, :poly, :ex, :hen, :hru, false)"
            " ON CONFLICT (track, normalized_word) DO NOTHING"
        ),
        [
            {
                # Normalised here rather than with lower() in the statement:
                # one bind cannot serve both a varchar column and lower(), and
                # asyncpg refuses to guess which type was meant.
                "w": w, "norm": w.lower(), "t": t, "lvl": lvl, "rank": rank,
                "poly": poly, "ex": ex, "hen": hen, "hru": hru,
            }
            for w, t, lvl, rank, poly, ex, hen, hru in WORDS
        ],
    )


def downgrade() -> None:
    op.get_bind().execute(
        sa.text(
            "DELETE FROM words WHERE track = 'en' AND normalized_word = ANY(:names)"
        ),
        {"names": [w.lower() for w, *_ in WORDS]},
    )
    op.drop_column("words", "polysemous")
